### ISSUE TITLE
Q: Steal a certain item

### ISSUE THREAD

**Issue by VirusNik21** [Saibot393/LocknKey#101]
QUESTION:
Is it possible to remove an item from the list of possible thefts? 
For example, so that not all objects, but only certain ones, can be removed from a goblin’s corpse or master charater to steal?

**Comment by Saibot393** [comment]
Not yet. I plan on adding something soon, that allows a more detailed way of setting what can/can't be stolen and setting a DC per item. I currently don't quite have the time to do so, it will probably take 1-1.5 months until i get around to it.

**Comment by Saibot393** [comment]
I have added item type filters and item based DCs with v3.1.0
