### ISSUE TITLE
Duplicate keys in the en.json file

### ISSUE THREAD

**Issue by Lioheart** [Saibot393/LocknKey#102]
Duplicate in row 67 and 78
![obraz](https://github.com/Saibot393/LocknKey/assets/39154364/4015d263-9149-4c56-818a-ef85a40d7af8)

**Comment by Saibot393** [comment]
Good catch. I will probably not make a seperate relase to remove them since it doesn't affect the behaviour but i will remove it with the next version, thanks.

**Comment by Saibot393** [comment]
I have removed the duplicate keys with v3.0.4
