### ISSUE TITLE
Dice rolling not correct for Savage Worlds Adventure Edition

### ISSUE THREAD

**Issue by Deadlander** [Saibot393/LocknKey#106]
The Savage Worlds system uses exploding dice for all rolls. Currently, LocknKey does not support the dice exploding on the top number of the die (i.e. when rolling a d6 for Thievery and the d6 Wild die, neither will explode when rolling a 6 on the dice).

This can be partially fixed by adding a x to the Wild Die portion of the formula, but I am unsure how to correct the formula to make the Skill die explode as well. 

The original formula in the mod is {1d@skills.Thievery.system.die.sides,1d6}kh + @skills.Thievery.system.die.modifier
Correcting the Wild die portion makes it look like this: {1d@skills.Thievery.system.die.sides,1d6x}kh + @skills.Thievery.system.die.modifier

Is there a way we can modify the Skill portion formula to make that die explode as well? 
This problem also extends to the Athletics roll for breaking the lock as well.

Any help would be greatly appreciated!

**Comment by Saibot393** [comment]
I didn't know about the exploding rule, thank you.

I think this formula should work: `{1d@(skills.Thievery.system.die.sides)x,1d6x}kh + @skills.Thievery.system.die.modifier`

I will update the formulas with the next version

**Comment by Deadlander** [comment]
Thanks! I will give it a try and see if that is indeed the fix!

**Comment by Saibot393** [comment]
Just noticed a type, should have been `{1d(@skills.Thievery.system.die.sides)x,1d6x}kh + @skills.Thievery.system.die.modifier`, sorry

**Comment by Deadlander** [comment]
Works like a charm! Thanks!

**Comment by Saibot393** [comment]
Glad to hear that, thanks for confirming. I will include the changes with the next update.
