### ISSUE TITLE
Key ID not unlocking Doors?

### ISSUE THREAD

**Issue by CalmRainman** [Saibot393/LocknKey#107]
I have created a key for a door using the GM commands, and assigned ownership of it to a test player. For some reason, when I play as the tester, it says that I have no matching key. Am I understanding the module incorrectly? The only time they can unlock the door is if I add them to Identities, and then they can lock/unlock without the key. 
![image](https://github.com/user-attachments/assets/7fde4b85-134c-47f3-afe6-d675a20f77a9)

**Comment by Saibot393** [comment]
When you say you have assigned ownership of the key to the play, do you mean you have set the player as owner in the permissions menu? For a key to work the player has to have the key in their inventory.

**Comment by CalmRainman** [comment]
That is exactly what I was doing incorrectly. Thank you! I am still new to Foundry, and I thought those were the same things.

**Comment by Saibot393** [comment]
Glad to hear that that solved the problem. Have fun with discovering foundry.
