### ISSUE TITLE
Manifest Error

### ISSUE THREAD

**Issue by devteamplus** [Saibot393/LocknKey#111]
I'm getting an error when attempting to update.  I'm currently on version 3.1.4.  This error shows when I attempt to update.

![image](https://github.com/user-attachments/assets/a995684c-736e-4281-a17f-0e903ea4c39a)

FVTT version: 12 b331

**Comment by Saibot393** [comment]
For some reason github did not like my previously uploaded module manifest. Should now be fixed

**Comment by devteamplus** [comment]
Beautiful... works now.  Thanks!

**Comment by devteamplus** [comment]
Ooops.. meant to close this.  Here we go.
