### ISSUE TITLE
PF2e rolls not recognized for lockpicking

### ISSUE THREAD

**Issue by TravisWisecup** [Saibot393/LocknKey#112]
Unsure if this is an unimplemented feature or an issue. I tried setting up some simple doors to test lockpicking alongside PF2e, but every time I tried to configure the rolling with System Rolls it would not recognize any of the rolls as successes nor as failures. It would allow the player to roll, but every time it would say "...failed to pick the lock" or whatever the default failure message is. The roll and results would show up in the chat, but not count towards any successes or failures.

I tried setting the # of successes to all sorts of things such as 0/1, 1/0, 1/1, 5/5, 0/3, among some others. When I started testing as the GM after switching off System Rolls (which turned off bonuses from spells such as Knock) is when I first started seeing successes. I tried testing as a player with the module's rolls and that worked as well. It was only when I turned System Rolls on (before and after) that the system rolls were not acting as successes or failures.

**Comment by Saibot393** [comment]
The bug should now be fixed with v3.1.6.

**Comment by TravisWisecup** [comment]
Can confirm that successes/crit successes with system rolls now count as 1, and 2 successes respectively against a locked door. Critical failures with system rolls don't seem to remove lockpick (not sure if this is counted as Lock and Key custom Crit settings), but thought I'd mention it just in case.

![image](https://github.com/user-attachments/assets/c8d9e94e-c7e0-4f9b-a4b7-1156eab22dac)
![image](https://github.com/user-attachments/assets/6a4bf672-9423-4825-a923-bdf871d3e82d)

**Comment by Saibot393** [comment]
That bug should now also be solved with v3.1.7

**Comment by TravisWisecup** [comment]
It now correctly removes Thieves' Tools, but unfortunately doesn't recognize Replacement Picks as an option for lockpicking anymore if no Thieves' Tools are in the inventory. 

Unfortunately there doesn't seem to be any native features to set items to a status of broken, otherwise I'd suggest setting the Thieves' Tools to broken status, but allow lockpicking if they had broken Thieves' Tools and at least 1 quantity of replacement picks.

Maybe if they have both Thieves' Tools and Replacement picks you could start by removing the replacement picks first and then remove the Thieves' Tools last, or set the quantity of Thieves' Tools to 0 rather than deleting them, and if they have replacement picks it will and quantity of Thieves' Tools == 0 then allow to lockpick?

**Comment by Saibot393** [comment]
If the Replacement Picks are set as a replacement item in the Thieve's Tools Lock & Key settings they should be consumed before the thieves tools

**Comment by TravisWisecup** [comment]
My bad, I had thought that was on the list already.

Thanks so much for your quick resolutions and awesome module!

**Comment by Saibot393** [comment]
You are welcome, glad to hear that you enjoy the module
