### ISSUE TITLE
Auto landings bug? (MATT)

### ISSUE THREAD

**Issue by Farsun486** [Saibot393/LocknKey#114]
![image](https://github.com/user-attachments/assets/c724d4d9-75bd-484a-acd0-cc361a94c02c)

For whatever reason, the auto landings for lock and key aren't picking anything up at all, no matter what settings on either module I play around with or whether or not I use the _. I raised the issue in the MATT discord and they haven't used it much themselves so can't really comment. With all the foundry, system, and module changes recently, would you mind just double checking if they function correctly on your end so I can see if it's just a me issue or a wider bug?

TIA!

**Comment by Saibot393** [comment]
So everything seems to work correctly for me. Could you send me screenshots of your MATT tile settings (including Triggers>Setup and Triggers>Actions) and of the triggering door/token/tile (both the Lock & Key settings and the trigger settings)? Also, what exactly are your trigger conditions (i.e. which kind of object triggers the tile upon which action?)

**Comment by Farsun486** [comment]
Hi, 
I've tried it again and suddenly it's working, I've no idea what I was doing wrong but I'll take it!

**Comment by Saibot393** [comment]
Strange but happens sometimes. Glad to hear that it works, should it come up again, feel free to reopen the issue.
