### ISSUE TITLE
Pick pocketing DC is always null

### ISSUE THREAD

**Issue by Stonedtroll** [Saibot393/LocknKey#116]
Pick pocketing DC is always null regardless of what is put in the global setting for **Pick Pocket Default DC** and **Pick Pocket Default DC Formula**

Lock & Key v3.1.7
Foundry v12.331
D&D5e v3.3.1

**Comment by Saibot393** [comment]
So first thing, the default is only applied when the value has never been changed manually, to test the default value i would recommend using a new "clean" token just to be sure.
The default value is not applied should there be anything in the "Pick pocket default DC formula" setting, so should there be any error in the formula this might cause the default to misbehave, what are your default formula and value set to?

**Comment by Stonedtroll** [comment]
These are the scenarios I have tested with a new token:

![image](https://github.com/user-attachments/assets/044fc37a-c720-45df-87ca-1b79a03d53fe)

![image](https://github.com/user-attachments/assets/91bfb801-74bb-499f-b6d9-de1c60f8676d)

Expected behaviour is that pick pocketing is impossible.

![image](https://github.com/user-attachments/assets/38ac6638-dc86-49c9-ad7f-9aa1f240fee0)

![image](https://github.com/user-attachments/assets/6b6e6d5b-c919-45bc-a76d-f34dd66611df)

Expected behaviour is that pick pocketing failed.

Same results for these test cases as well

![image](https://github.com/user-attachments/assets/7e0dedd4-e62c-4373-917c-654e4ffedc91)

![image](https://github.com/user-attachments/assets/a18803e9-fec5-46fc-9e9c-46f2396c819d)

No errors were thrown. Console shows no messages related to the pick pocketing event.

If I go to the individual Token setting and put a -1 there, the behaviour is correct.

Let me know if you need more info.

**Comment by Saibot393** [comment]
could you send me the tokens actors .json export?

**Comment by Stonedtroll** [comment]
Picpocketer

[fvtt-Actor-riswynn-(dwarf-rogue)-RNh5ATxMLm3gbFiF.json](https://github.com/user-attachments/files/16922979/fvtt-Actor-riswynn-.dwarf-rogue.-RNh5ATxMLm3gbFiF.json)

Pickpocketee

[fvtt-Actor-skeleton-zga1EuI6s0btSA3N.json](https://github.com/user-attachments/files/16922981/fvtt-Actor-skeleton-zga1EuI6s0btSA3N.json)

**Comment by Saibot393** [comment]
So, the problem was, that the tokens PickPicketDC was set to `null`, overriding the default values.
I have released an improvement/fix for this behaviour with v3.1.8, this version will now override `null` values with the set default values.

**Comment by Stonedtroll** [comment]
You, sir, are a champ!
