### ISSUE TITLE
Key not creating 

### ISSUE THREAD

**Issue by Twitcher1000** [Saibot393/LocknKey#117]
When i create a key using the binding it doesn't get added to my items and the id is not generated I'm on pf2e most recent update and v12 foundry i have also recently updated L&K.

**Comment by Saibot393** [comment]
Are there any errors in the console when doing so? 
When you have "Key creation menu" activated, does the menu show up?
Have you tried the key creation in a clean world/ have you tried running [Find the culprit](https://foundryvtt.com/packages/find-the-culprit/)?

**Comment by Twitcher1000** [comment]
Sorry for the late reply, so odd thing when i sent that every time i pressed the create a key keybind the menu would open but no key would show in the folder now when i use the keybind no menu pops up, I used find the culprit on clean mod list same thing no menu, Lastly I checked the console while spamming the keybind and there were errors showing up. Ill post the errors below

Uncaught (in promise) TypeError: (intermediate value).Systemdefaultitemtype is not a function
[Detected 1 package: LocknKey(3.1.8)]
    Keyitemtype https://walgrim.moltenhosting.com/modules/LocknKey/scripts/utils/LnKutils.js:342
    createKeyItem https://walgrim.moltenhosting.com/modules/LocknKey/scripts/utils/LnKutils.js:332
    newLockKey https://walgrim.moltenhosting.com/modules/LocknKey/scripts/LockManager.js:464
    CreateNewKeyhoveredGM https://walgrim.moltenhosting.com/modules/LocknKey/scripts/LockManager.js:899
    onDown https://walgrim.moltenhosting.com/modules/LocknKey/scripts/settings/LnKSettings.js:586
    _executeKeybind https://walgrim.moltenhosting.com/scripts/foundry.js:2462
    _processKeyboardContext https://walgrim.moltenhosting.com/scripts/foundry.js:2503
    _handleKeyboardEvent https://walgrim.moltenhosting.com/scripts/foundry.js:2561
    _activateListeners https://walgrim.moltenhosting.com/scripts/foundry.js:2175

**Comment by Saibot393** [comment]
The bug that caused this error should now be fixed with v3.1.9

**Comment by Twitcher1000** [comment]
I've tried it and everything works now thank you very much.

**Comment by Saibot393** [comment]
Glad to hear that
