### ISSUE TITLE
PF2E double clicking to pickpocket show actor name

### ISSUE THREAD

**Issue by uniwars** [Saibot393/LocknKey#118]
Hi, when double clicking to pickpocket if the target is out of reach it will show its name to player, even if token/actor should not show their name by being in the opposition

![image](https://github.com/user-attachments/assets/73d25170-62c2-4967-a04b-aef0b0b5ef8f)

**Comment by Saibot393** [comment]
I will add a filter for that

**Comment by Saibot393** [comment]
I have fixed that bug with v3.2.0, sorry for the long wait
