### ISSUE TITLE
Limit the amount that can be taken during a lockpick

### ISSUE THREAD

**Issue by Stonedtroll** [Saibot393/LocknKey#121]
Currently, players can take the kitchen sink. Would it be possible to limit the total weight of items taken in a single pick pocketing attempt? Or randomly pick just one?

**Comment by Stonedtroll** [comment]
Thank you!

**Comment by Saibot393** [comment]
I have added settings to limit the loot via the total amount of items or their weight, depending on the pick pocket success level with v3.2.0

**Comment by Stonedtroll** [comment]
Thank you!
