### ISSUE TITLE
I'd like to share a macro for pickpocket

### ISSUE THREAD

**Issue by fedeicodip** [Saibot393/LocknKey#122]
Hi Saibot, thank you for Lock and Key. Now the pickpocket feature makes it easier to give some items to the players. Nice also that you can make dead corpses lootable.
I wrote a macro that thiks makes it easier to change some pickpocket DC values on the fly. Just wanted to share it. Hope it helps someone and maybeyou wish to add it to the macros with the addon.
[PickpocketDC.txt](https://github.com/user-attachments/files/17688817/PickpocketDC.txt)
Let me know if you like it. I'm not an expert in javascript nor with github so forgive me if I haven't been enough accurate and feel free to change/delete anything

**Comment by Saibot393** [comment]
Thank you, that seems to be a really useful macro. I will look into adding the macro with the next update.

**Comment by Saibot393** [comment]
I have added your macro with v3.2.0, thanks again
