### ISSUE TITLE
Make a Thieves Tool dissapear after any try to lockpick the door?

### ISSUE THREAD

**Issue by hansbieli** [Saibot393/LocknKey#123]
Is that somehow doable by myself or would you need to code that by yourself, dont want to pose any trouble but as a GM who doesnt rly trust their players that would be a great feature

**Comment by Saibot393** [comment]
Currently they will only break on a critical fails or the amount of attempts per door can be limited, i will look into adding an option for lock picks to be removed per attempts with a future update.

**Comment by Saibot393** [comment]
I have added more settings for when the lock pick will be removed (never, always, failure, critical failure)
