### ISSUE TITLE
Question about players with multiple keys/locks?

### ISSUE THREAD

**Issue by teequillin** [Saibot393/LocknKey#127]
I have set up a scene with multiple locks that match very specific keys in Foundry. After setting it up, it dawned on me that if one PC has collected all of the keys on the map into their inventory, then they can successfully open all of the locks on the map merely because they have them all in their inventory. (The point of the puzzle/map is that they have to match the correct key with the correct lock or it triggers The Bad Stuff; ideally, they get to screw up on 5 of the 11 locks before the Bad Stuff happens, but still…)

Is there a way to force my players to make a choice of which key to try on a specific lock if they happen to have all 11 keys to all 11 locks on them when they try to open any of the 11 locks?

Thanks,
Tee

**Comment by Saibot393** [comment]
Currently not, but thats an interesting idea. I will look into adding such a feature

**Comment by teequillin** [comment]
If I turn off the option to allow players to right click a locked container, would that force them to choose which key to use on a locked container from their inventory?

**Comment by Saibot393** [comment]
I am not quite sure which setting you mean exactly, but it will probably only mean, that the "use key" option from a menu, but not which key

**Comment by Saibot393** [comment]
I have added a per door setting (and a world default setting) to require players to select which key item to use via a window with v3.2.0

**Comment by teequillin** [comment]
That is fantastic!! Thanks! Sent from my iPhoneOn Dec 23, 2024, at 7:41 AM, Saibot393 ***@***.***> wrote:﻿
I have added a per door setting (and a world default setting) to require players to select which key item to use via a window with v3.2.0
