### ISSUE TITLE
Feature request - Critical fail jams the lock

### ISSUE THREAD

**Issue by Tatonker** [Saibot393/LocknKey#14]
Would it be possible to set up the critical fail condition to either break the lock pick (remove it) or cause the lock to become jammed and un-pickable?

I would like my players to have some risk involved but not worry about losing their ability to attempt further lock pick attempts on other locks.

**Comment by Saibot393** [comment]
I will probably get this done over the weekend

**Comment by Saibot393** [comment]
The jammed feature has been implemented with v1.8.0
