### ISSUE TITLE
[Feature Request] Add the settings "Lockpick items" from the module settings list to the Lock and Key panel settings list

### ISSUE THREAD

**Issue by p4535992** [Saibot393/LocknKey#18]
With my group of "newbies," we have finished testing the module and there are some things we could use (even on commission). I can also try to do a PR myself, but you tell me what you think first.

The use case: A door can only be lock picked (lock picking not a direct open with the key) by a "Diamond of Discord" object, putting the name (or compendium id) of the object in the module settings works, but I would like the ability to be able to set this setting in the Lock and Key panel (image below), to do abstruse things like setting a specific object for each door.

![](https://i.imgur.com/Xr4tduJ.png)

For my use case, it would be fine to use the same mechanism as for keys (with optional object destruction, etc.), with the difference being that upon right-clicking, the lockpiking roll is triggered instead of the automatic door opening

**Comment by Saibot393** [comment]
I will add an option for that to the next update. The update will probably release towards the end of the week.

**Comment by Saibot393** [comment]
I have added a "Special Lockpick" setting to locks with v1.9.0
