### ISSUE TITLE
[Feature Request] When creating a key with the command "shift+right-click" add a dialog for choose the destination folder and the name

### ISSUE THREAD

**Issue by p4535992** [Saibot393/LocknKey#19]
With my group of "newbies," we have finished testing the module and there are some things we could use (even on commission). I can also try to do a PR myself, but you tell me what you think first.

The use case: People (even me in the beginning) would start "shift+right-click" in bursts and not understand how and where the "key" was created . Once they realized it was in the items sidebar, they could not distinguish between the "key" created by me and the "key" created by someone else.

A dialog at the act of "shift+right-click," with the ability to choose the destination folder and the name of the item key  would allow a more controlled flow of the whole thing.

**Comment by Saibot393** [comment]
I will add an option for that to the next update. The update will probably release towards the end of the week.

**Comment by p4535992** [comment]
NO rush take your time, by the way can you add a funding link  on the project (my suggestion a kofi link)? I don't mind giving something for a request of mine.

**Comment by Saibot393** [comment]
I was planning on adding a few things anyway this week and the requested features should be relatively manageable. In regards to a funding link i am not quite sure, it feels like guaranteeing a certain level of time commitment/quality which i may not always be able to do.

**Comment by Saibot393** [comment]
I have added an optional "Key creation menu" with v1.9.0
