### ISSUE TITLE
Feature request : Pf2e Lockpicking particularities

### ISSUE THREAD

**Issue by uniwars** [Saibot393/LocknKey#2]
Hi, I would like to ask considering adding a more detailed support of Pf2e lockpicking by adding some or all of the features :

- Having a way to set a number of success required to lockpick, by door/container.
Success on thievery skill = 1 succes to unlock, crit succes = 2 success
In Pf2e nat 20/1 = 1 degree of succes higher/lower for the result, and result +10 vs dc = crit and result -10 vs dc = crit fail

- Critical Failure You break your tools. Fixing them requires using Crafting to Repair them or else swapping in replacement picks (costing 3 sp, or 3 gp for infiltrator thieves’ tools).
Maybe check for replacement picks in the inventory and delete one on crit fail

-Make the roll to pick a lock counts as a "pick a lock" action so bonus added only to that action would auto apply

**Comment by Saibot393** [comment]
The first 2 features are quite doable and will probably be added in one of the next releases (maybe next week). The last feature is very Pf2e specific and may not be possible with the way i implemented the skill check. I will however add an option to characters to add a custom "lock pick" bonus.

**Comment by uniwars** [comment]
Thanks the quick answer, I was wondering : is it possible to lock pick a container like a pf2e loot ? I saw in the update the dc to lock pick is in the door settings, but there is no such setting for loot actor

**Comment by Saibot393** [comment]
Thats strange. The Lock DC setting should be available for the Pf2e Loot actors. Does the Lock & Key option tab show up in token settings of Loot actors for you?

**Comment by uniwars** [comment]
Found it, sorry, I was looking in the actor sheet

**Comment by Saibot393** [comment]
No problem! Enjoy the module.

**Comment by Saibot393** [comment]
The last point can now be done "simulated" by adding lockpicking boni to tokens. Critical failures/successes will be added in the next release (maybe this weekend, unless bug fixes have te be prioritized)

**Comment by Saibot393** [comment]
Both the number of required successes and the behaviour on critical results for lock picking has been added with v1.4.0
