### ISSUE TITLE
[Feature Request] Chat message modification when Lock Picking. Replace the text "XXX succeeded at picking the lock" with "XXX succeeded at picking the lock  with item YYY"

### ISSUE THREAD

**Issue by p4535992** [Saibot393/LocknKey#20]
With my group of "newbies," we have finished testing the module and there are some things we could use (even on commission). I can also try to do a PR myself, but you tell me what you think first.

The use case: In the chat message at the time of lock picking, it is not written with which object you were able to lock pick .
Some may prefer it that way, what I am asking for is the possibility (with a setting most likely) to be able to print in chat also the object with which lockpicking was done.

So the message "XXX succeeded at picking the lock" changed to "XXX succeeded at picking the lock  with item YYY" 

and if  critical fail:

"XXX has critical failed at picking the lock  with item YYY, the item is broken!"

**Comment by Saibot393** [comment]
I have added an option to mention the used lockpick (including if said lock pick broke) with v1.9.0
