### ISSUE TITLE
[Feature Request] Add logic to pop-up menu for actions

### ISSUE THREAD

**Issue by ottyn** [Saibot393/LocknKey#22]
I would like to suggest some additional sanity logic added to the action pop-up menu when you right click on a door.  By this I mean if the lock is Jammed and the setting for Jammed locks can't be picked is checked, then it shouldn't present the option to pick the lock in the menu.  Same if you don't have the matching Key for the door it should not present the option to use a key, or clicking that should give some scrolling text or chat message that you don't have the correct key.

If either of the DC boxes are set to -1 (not possible to pick/break down) then it should not present those options in the menu either.

Not sure how easy this would be to implement, but I think this would make it easier on players as a whole and save time for the GM.

BTW, Love the direction and updates you have been providing for this!

**Comment by Saibot393** [comment]
Good idea, should be relatively easy to implement. I will add it to the next update.

**Comment by Saibot393** [comment]
The unavailable interactions will no longer show up with v1.9.1 (unless you explicitly turn them on in the settings)
