### ISSUE TITLE
Add item to tab class

### ISSUE THREAD

**Issue by Ikabodo** [Saibot393/LocknKey#23]
Hi! I think this would be a real easy one. 

Would you mind adding "item" to the classes of the tab?
This would make it more compatible with sheets such as TidySheet with very minimal changes.

From this:
![image](https://github.com/Saibot393/LocknKey/assets/7766890/aa809d52-81ab-4b64-801b-61144f2c0b76)

To this:
![image](https://github.com/Saibot393/LocknKey/assets/7766890/86df6aec-ea0a-436c-a64a-62c76f6333b7)

Just add this:
![image](https://github.com/Saibot393/LocknKey/assets/7766890/75de8a34-1c94-4267-b5f1-e72d9b575f2b)

**Comment by Saibot393** [comment]
Thanks for the suggestion and the included details. I will add it to the next update (probably tomorrow or so).

**Comment by Saibot393** [comment]
I have added the item class with v1.9.6
