### ISSUE TITLE
Add trap detection and disable trap functionality

### ISSUE THREAD

**Issue by Spuznik** [Saibot393/LocknKey#24]
The module is great but doesnt address traps and disabling them. Having a DC for Trap Detection and Trap Disarm would be a great addition.

Having a dialog popup on what you want to do, pick lock/ break down door/ break lock or disarm if detected would be amazing.

**Comment by Saibot393** [comment]
I will have a look into traps but i am not quite sure yet how to make them a) system independent and b) suport them UI wise.
A dialog pupup is already implemented under client settings>control sceme.

**Comment by mfozz** [comment]
Yeah, this would be great. I currently use Monk's Active Tile Triggers to simulate a trapped chest. There might be some way to offload the burden to another module like MATT or macros that the GM set up.

**Comment by Saibot393** [comment]
I spent a bit of time looking into it. I will probably go the route of using MATT for now and adding custom triggers (Lockpick fail/success, wrong password...). There is also a chance, that the event triggers tha will be introduced with v12 might be interesting for this purpose.

**Comment by Saibot393** [comment]
I have added integration for MATT with v1.11.0 which should be capable of handling most kinds of traps

**Comment by Spuznik** [comment]
Tested the Triggers, but cant get to work the ID keeps clearing when I update the Token.

**Comment by Spuznik** [comment]
![chrome_nKqOlKLxhi](https://github.com/Saibot393/LocknKey/assets/142272986/c1ad1176-f0e2-435a-9403-6c6a466aea44)

**Comment by Saibot393** [comment]
Sorry for that, should be fixed with v1.11.1

**Comment by Spuznik** [comment]
The fact that you added a way to manage it is more than enough. I love your modules and its great to see Baileywiki has been promoting them

**Comment by mfozz** [comment]
Yes, this is fantastic! I've tested it with a trap tile that triggers on a failed lockpick, and it seems to be working well.

One issue I've seen might be a limitation of MATT, so I'm not sure whether there's a way around it: 
Dialogs trigger from a MATT don't appear on the player side. I think it might be due to the limited options in the tile settings.

https://github.com/Saibot393/LocknKey/assets/89781047/ccb6579f-5bbf-4945-a289-5e8737781262

I've previously used the dialog to let players search for traps.

**Comment by Saibot393** [comment]
There might be something i can do about that, i will have to do a few tests.

**Comment by Saibot393** [comment]
I have just released v1.11.2, the popups should now be correctly displayed for the triggering user

**Comment by Saibot393** [comment]
While not directly related to Lock & Key it may still be relevant to trap detection: Another of my modules, [Perceptive](https://foundryvtt.com/packages/perceptive), now supports spotting (passive or active) of invisible tiles.

**Comment by Spuznik** [comment]
I have tested it and it has the potential to do this, but only if you use
invisible tokens, tiles. If you add a trigger to the detection it would
allow for effects on tokens and tiles like this.[image:
chrome_xrfBUQY8ke.gif]

Currently I use a tile and trigger a passive skill check, but your
perceptive script would eliminate the need.

**Comment by Saibot393** [comment]
[Perceptive v2.6.0](https://github.com/Saibot393/perceptive/blob/v2.6.0/CHANGELOG.md#v260) add the MATT triggers for spotting
