### ISSUE TITLE
Error on Break Lock

### ISSUE THREAD

**Issue by ottyn** [Saibot393/LocknKey#25]
Foundry 11.308
PF2e 5.4.2
Lock & Key 1.9.7

Ran into this issue last night during our session.  When player right-clicks on a locked door and gets the dialog popup, they select Break Lock.  They then get the following error message.
![error](https://github.com/Saibot393/LocknKey/assets/97130150/c227dc48-95ea-4b25-b710-31848da11a79)

Door and Lock & Key settings on the wall:
![door_setup](https://github.com/Saibot393/LocknKey/assets/97130150/777b3772-18ac-4eda-9b43-7f0447ee0b00)
![lock-key_setup](https://github.com/Saibot393/LocknKey/assets/97130150/2139a9cb-4106-413f-8fcc-a1fcfcdd97ae)

**Comment by Saibot393** [comment]
Are you using the world setting Pf2e roll integration? In this case i also just discovered this bug. The Pf2e seems to have changes a few things regarding rolls in the last update. I just released v1.9.8 which should fix this bug

**Comment by ottyn** [comment]
Just updated to Lock & Key 1.9.8.  Issue appears to be resolved after clearing the browser cache and hard reloading.  Thank you for the quick response and fix!
