### ISSUE TITLE
Lockpicking doesn't unlock doors

### ISSUE THREAD

**Issue by noctxpyre** [Saibot393/LocknKey#26]
When a player rolls to lockpick a door nothing happens after the roll. I don't know if this is supposed to be normal and I as the GM have to unlock the door manually then or I'm doing something wrong, but just wanted to tell you.

Foundry v11.308
DnD5e v2.3.1

**Comment by Saibot393** [comment]
That is a bug, the door should be unlocked (or locked) automatically, few questions:

1. When the player rolls the check, do any messages show up the chat and if so, what is their content?
2. What modules do you have installed?

**Comment by noctxpyre** [comment]
Active Modules:
----------
About Time v;
Action Pack v;
Active-Auras v;
Active Token Effects v;
Archon (Masked Items) v;
Autocomplete Inline Properties v;
Automated Animations v;
Boneyard Turn Timer v;
Break Time v;
Build-a-Bonus v;
Chris's Premades v;
Cleaner sheet title bar v;
Compendium Folders v;
D&D5e Animations v;
DDB-Importer: A D&D Beyond Integrator v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dice Tray v;
Dynamic effects using Active Effects v.3;
Effect Macro v;
Follow Me! v;
Foundry Achievements v;
FXMaster v;
Item Macro v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
Let Me Roll That For You! v;
Let's Trade 5e v;
Levels v;
Library - Color Picker v;
Library - Color Settings v;
Library - libWrapper v.0;
Library - socketlib v;
Limits v;
Lock & Key v;
Midi QOL v;
Module Compatibility Checker v;
Module Management+ v;
Party Overview v;
Perceptive v;
Polyglot v;
Quick Grid Align v;
✋ Raise My Hand v;
Rarity Colors v;
Rest Recovery for 5E v;
Roll of Fate v;
Sequencer v;
Simple Calendar v;
SmallTime v;
Small Visual Tweaks v;
Stealthy v;
Tagger v;
Template Macro v;
TheRipper93's Module Hub v;
Tidy5e Sheet v;
Times Up v;
Token Attacher v;
Token Auras v;
Token Frames v;
Token Info Icons v;
Tokenizer v;
Token Magic FX v;
UI - Minimal UI v;
UI - Tidy UI - Game Settings v;
Vadanx's Combat Orchestrator v;
Vision 5e v;
Visual Active Effects v;
Wall Height v;
Warp Gate v;

Inactive Modules:
----------
Health Estimate v;
![Bild_2023-09-08_002837771](https://github.com/Saibot393/LocknKey/assets/97793475/2352b9e5-71e9-4d7b-ab21-1ab3fc3d0d8a)

**Comment by Saibot393** [comment]
Normally a result should be shown after the roll itself. Do any errors poup in the console (of bothGM and player) (F12) when a player tries to lock pick?

**Comment by noctxpyre** [comment]
I reinstalled the module, now it's working fine.

**Comment by Saibot393** [comment]
Perfect, was probably just a strange loading bug
