### ISSUE TITLE
Right-Click Popup menu not Showing when Arms Reach is acitve.

### ISSUE THREAD

**Issue by Chelebi** [Saibot393/LocknKey#27]
So i just found this Module and was trying it out on Foundry V11.308 on the D&D 5e system (v2.3.1)

I changed the Client Settings control sceme to right-click popup-menu and noticed the popup didn't show up when right clicking a door.
it did show up when enabling the Show all lock interactions when right clicking a token but none of the buttons did anything.

since i have multiple modules installed i disabled all and after reactivating them one by one i found out that the popup menu breaks when i use Lock & key together with Arms Reach (Current version 2.3.3) even tho both Modules show they are compatible.

**Comment by Saibot393** [comment]
I just released v1.9.9 which should fix this problem
