### ISSUE TITLE
[Feature Request] Additional Lockpick Tools for PF2e

### ISSUE THREAD

**Issue by ottyn** [Saibot393/LocknKey#28]
The default Thieves' Tools are listed as lockpicks in the Lock & Key settings automatically.

![image](https://github.com/Saibot393/LocknKey/assets/97130150/e88a086f-a078-4673-bd53-7998e489b3ae)

The list of additional lockpicks should probably also be added so that players don't receive a warning that they do not have lockpicks in their inventory.  There may be others, but these are the ones I could find in the system.

List by UUID:
zvLyCVD8g2PdHJAc (Thieves' Tools)
6nrCxNQFycUVFOV2 (Thieves' Tools Infiltrator)
Ejmv9IHGp9Ad9dgu (Thieves' Tools Concealable)
QnuL1UEot8ptWNb1 (Encompassing Lockpick)
spqcRLBsMOC9WTcd (Keymaking Tools)
fprUZviW8khm2BLo (Skeleton Key)
AFE073UYI0mkWuUs (Skeleton Key Greater)

**Comment by Saibot393** [comment]
Thank you. I will add them to the next update.

**Comment by Saibot393** [comment]
I have added the new IDs with v1.9.12
