### ISSUE TITLE
Little error with MIDI QoL

### ISSUE THREAD

**Issue by p4535992** [Saibot393/LocknKey#29]
Lock and Key Version: 1.9.9

Midi Version:  11.0.20.1

![](https://i.imgur.com/WX0uAwa.png)

Sorry about the little information, the original issuer just give me this screenshot,

**Comment by p4535992** [comment]
Nevermind i see the latest version is 1.9.12

**Comment by Saibot393** [comment]
I thin this error should persist in v1.9.12
