### ISSUE TITLE
Feature request : Force open option

### ISSUE THREAD

**Issue by uniwars** [Saibot393/LocknKey#3]
Hi, I would like to ask considering adding "Force open" support for Pf2e system, but I think it can apply to more systems :

"Using your body, a lever, or some other tool, you attempt to forcefully open a door, window, container or heavy gate. With a high enough result, you can even smash through walls. Without a crowbar, prying something open takes a –2 item penalty to the Athletics check to Force Open.

Critical Success You open the door, window, container, or gate and can avoid damaging it in the process.
Success You break the door, window, container, or gate open, and the door, window, container, or gate gains the broken condition. If it’s especially sturdy, the GM might have it take damage but not be broken.
Critical Failure Your attempt jams the door, window, container, or gate shut, imposing a –2 circumstance penalty on future attempts to Force it Open."

- Athletics DC per door/container
- Check for crowbar to remove the malus.
- Check for Pf2e 4 degrees of success and nat 1/20 and +10/-10 rules

**Comment by Saibot393** [comment]
A general force open interaction will be relativ easy to implement. I will try to add it in the next version. The Pf2e specific rules however are a bit more complex and will probably be added in a later release.

**Comment by Saibot393** [comment]
This feature has been added in v1.3.0. You will however have to add the crowbar bonus manually to the item settings of crowbars items. I will probably add a pack with custom items that already have these bonuses in one of the next releases. The critical success/failure system is also not implemented yet and will be added in the next release (unless bug fixes have te be prioritized).

**Comment by Saibot393** [comment]
Version 1.6.0 improved the compatibility with the Pf2e system, may be relevant to this request

**Comment by Saibot393** [comment]
I have added integration for MATT with v1.11.0 which should be capable of handling things like dealing damage to tokens on failure.
