### ISSUE TITLE
Item piles - Conteiner

### ISSUE THREAD

**Issue by rinnocenti** [Saibot393/LocknKey#31]
When the  Item Piles is in "Container" or "Vault" mode, the locked options do not appear. 
They only appear on the token when it is in item piles mode is "Item Pile".

Bonus: If possible, when the picklock is successful, you could also change the container option to "unlock" to integrate the two modules.

**Comment by Saibot393** [comment]
I have just released v1.10.1 which adds support for both Item piles Containers and Vaults. Item Piles locked containers will also be automatically unlocked when unlocked with Lock & Key. Notice though, that Lock & Key messages will not popup for Item-Piles locked tokens.
