### ISSUE TITLE
Replacement Items not in Config

### ISSUE THREAD

**Issue by Peach774** [Saibot393/LocknKey#33]
You added a replacement items setting, but I don't see it in the config anywhere. I think something might be missing here.

**Comment by Saibot393** [comment]
Thats strange. Normally the setting should appear at the end of an items Lock manipulation settings: 
![image](https://github.com/Saibot393/LocknKey/assets/137942782/7df464d1-293a-4e95-84b4-1b233c0cf5f9)
Do all the other settings show up for you?

**Comment by Peach774** [comment]
OH - I assumed it was a general setting, like in the same area as setting lockpick items.

**Comment by Saibot393** [comment]
I chose to put this setting into the item settings, since there is a chance, that some lock pick types do not have replacements/ that some lock picks have different replacements.

**Comment by Peach774** [comment]
Ah ok - thank you for explaining how this works. I appreciate the clarification.
