### ISSUE TITLE
Used with Item Piles and it shows OpenImage but its locked.

### ISSUE THREAD

**Issue by Maradeurfv** [Saibot393/LocknKey#34]
If a PC trys to doubleklick a chest f.e., wich is locked, Item Pile shows the OpenImage although its already locked. What is my failure?

**Comment by Saibot393** [comment]
What exactly do you mean with the "OpenImage"?

**Comment by Saibot393** [comment]
Do you mean this lock symbol to the right of a container item pile?
![image](https://github.com/Saibot393/LocknKey/assets/137942782/c3d5c2a7-5124-494b-adfc-62a2cbacc1fd)

**Comment by Maradeurfv** [comment]
hi, thx for the feedback. was not able to reproduce it. if so, i will take screens and post them here.

**Comment by Saibot393** [comment]
That was an oversight on my part. I have released v1.10.3 which should sync the lock state bewteen lock & key and item piles containers correctly and thereby solve this bug.
