### ISSUE TITLE
Multiple Scrolling Text Overlapping

### ISSUE THREAD

**Issue by ExileofBrokenSky** [Saibot393/LocknKey#35]
When a player tries to lockpick a door and fails critically, using the module option to jam the lock (PF2e style) and to subtract the picklock you get this:
![image](https://github.com/Saibot393/LocknKey/assets/28786777/0a120c55-a9dc-404b-b199-93addcb1f6e7)
"lockpick broken" and "Jammed the Lock" overlap.
Suggest a queue of scrolling texts with a small delay, or concatenating simultaneous scrolling texts.

**Comment by ExileofBrokenSky** [comment]
Separate issue, but now that PF2e has a party sheet, the system default hotkey for opening the party sheet is 'P' which overrides Lock & Key's default picklock hotkey.

**Comment by Saibot393** [comment]
I will look into it and see what i can do about the scrolling text. I am not quite sure yet where to put the new hotkey for pick lock, i am currently considering the ";"/":"/"ö" key.

**Comment by Saibot393** [comment]
I just released v1.10.5 which should resolve both issues
