### ISSUE TITLE
D35E System Support

### ISSUE THREAD

**Issue by Hyrkanus** [Saibot393/LocknKey#36]
It would be nice to include the formulas for the Dungeons & Dragons 3.5e system (https://foundryvtt.com/packages/D35E/).

The appropriate formulas are:
- Lockpick: 1d20+@actor.system.skills.opl.mod
- Break: 1d20+@actor.system.abilities.str.mod

That should be all to get it working.

(Foundry VTT v11.313 | D35E v2.3.2)

All the best and thanks for this useful module.

**Comment by Saibot393** [comment]
Sure, i will add it with the next update. Glad you enjoy the module.

**Comment by Saibot393** [comment]
I have added the default formulas and few other default values for D&D 3.5e with v1.10.6
