### ISSUE TITLE
System Compatibility: WFRP4 Fantasy roleplay

### ISSUE THREAD

**Issue by warhammering** [Saibot393/LocknKey#38]
Hello again :D
I wonder if it would be possible to create system compatibility with Warhammer fantasy roleplay.
The system works with success levels instead of rolling a die. I spoke to the creator and he says skills rolls in the systems are items and not data properties ( if that says anything to you) 
For example, if I have a thief I can use his picklock skills and I have to roll under the target number to succeed 
![image](https://github.com/Saibot393/LocknKey/assets/140810683/8b241181-7f3c-4ac5-956c-3abd10ce9dc0)
Based on the success level (the difference between the roll and the target I will be able to open a lock or not)
![image](https://github.com/Saibot393/LocknKey/assets/140810683/12ddfcce-2a38-4574-a992-9c32f5629f00)
There is also the expanded test, but this may be too complicated to implement. I was wondering if you could at least implement it for a success or fail option.

**Comment by Saibot393** [comment]
I will look into it and see what i can do

**Comment by Saibot393** [comment]
I just had a look at the rules for WFRP4 checks and would like to confirm with you, that i understood them correctly:
- A lock could have difficulty classes with an associated value (e.g. Very easy +60 or Very hard -30)
- When a player tries to pick this lock they would add their skill/attribute to this value (dex?) to get the target value and roll a d100
- If the player has rolled below or equal to this target they succeed, otherwise they fail
- If they player rolls a 1 they auto succeed, if they roll a 100 they auto fail
If these are they rules i can easily implement them, though locks would require the difficulty in numerical form

**Comment by warhammering** [comment]
Yeah, that is exactly the mechanics, awesome and thx you for taking the time to check it. 
It can be a bit more complicated but that you wrote it would be more than enough. If you want to get the full rules there are other things into consideration.
When you pass the role you get Success Levels SL. so for example you rolled a 20 in a target you get an SL of 3
There is also crit or fumble on doubles.
Let's say that you have a role to pass at 45, then 11, 22, 33, 44 would be crit, and the 55, 66, 77, 88, and 99 would be a fumble. I guess fumbles would be like the lock breaking or getting jammed
How the locksmith works here is the rulebook on that skill
![image](https://github.com/Saibot393/LocknKey/assets/140810683/d6b5259f-e562-4338-88e3-f697e6863a91)
But hey just with just that you wrote it would be super amazing like that that would be more than amazing. If you want to check. I have a thief in our game so any implementation it would be super awesome to get more for my players, so I super appreciate any effort or any way you could implement it

**Comment by Saibot393** [comment]
I have added the crit system with v1.10.7. The formula for lock picking to work is `1d100 - @actor.characteristics.dex.value`. I have split it into two crit systems, one with doubles as crits, one without. I have not yet implemented anything regarding Success Levels since i was not sure how exactly these would interact with crits and how exactly they differ in regards to the success (i could however add something where they influence the successes added to the door locking and crits double the SL). The doors dc is  equivalent to the systems numerical lock difficulty (remember to never use -1 since that gets translated into infinity). I will leave this issue open for now, incase there are any questions, bugs or further feature requests.

**Comment by warhammering** [comment]
I am a bit confused, what do you mean "The doors dc is equivalent to the systems numerical lock difficulty"

**Comment by Saibot393** [comment]
If you want the door to have a difficulty of e.g. Hard you set the DC to -20

**Comment by warhammering** [comment]
oh ok, that makes sense. I give it a try and I let you know. Thank you so much for doing this!

**Comment by warhammering** [comment]
Can I bother you with another question? I am trying to use lockpicks as an item to try to open doors but is not working, I am probably doing something wrong
![image](https://github.com/Saibot393/LocknKey/assets/140810683/59efc8a3-5a04-45d1-a713-c05415e50c79)
This is the item and I have this as the settings but is not working
![image](https://github.com/Saibot393/LocknKey/assets/140810683/696a7d29-604b-4ea0-bd72-33f4fb2266aa)
and this is the door
![image](https://github.com/Saibot393/LocknKey/assets/140810683/f74a7dfc-3f05-4ff1-b5ce-fefc59f2c30c)
I know I am doing something wrong but I don't know what is it

**Comment by warhammering** [comment]
btw, the rolling seems to be working. Is rolling dex instead of the skill in itself which is the lockpick skill which is based on dex but it has more points. for example 
my thief dex is 32
![image](https://github.com/Saibot393/LocknKey/assets/140810683/34585f48-bf39-4336-8594-ed43be8835d8)
but he allocates some points to his picklock skills which is 32 + 5 since he has added points to it
![image](https://github.com/Saibot393/LocknKey/assets/140810683/41732082-4576-45b1-9d2a-851fc40751e5)
so it should be running the skill instead of the raw dex.
How did you find out the formula for the roll?
I hope I am not bothering you too much :)

**Comment by Saibot393** [comment]
A nother question regarding your problem with lock picking, were you logged in as a player or as GM when you tested lock picking? In case you were logged in as a player, was a  GM account logged in at the same time?

**Comment by warhammering** [comment]
Yes, I was logged in as the GM and in another browser and another account I was using the player.

**Comment by Saibot393** [comment]
Were there any text popups above the door/do you have the text popups enabled?

**Comment by warhammering** [comment]
![image](https://github.com/Saibot393/LocknKey/assets/140810683/66f94a50-440c-42a9-8248-f29ba93f7706)
![image](https://github.com/Saibot393/LocknKey/assets/140810683/6552bb73-3222-4700-9532-d30a7a96df7d)

**Comment by warhammering** [comment]
this is when I use alt + right-click, to try to break the lock, now that I see the lock pick is working as intended :(, sorry for the confusion. It actually works when I use the lock picks using shift

**Comment by Saibot393** [comment]
No problem. I have not yet included a formula for lock breaking since i was not sure what the appropiate skill/attribute is in WFRP4, assuming it is a strength check the roll formula `1d100 - @actor.characteristics.str.value` should probably work

**Comment by warhammering** [comment]
ah ok, yeah, skills seems to be different, but I can use the current dex. If you have any possibility to get the skills working that would be amazing. Thx you for the hard work

**Comment by warhammering** [comment]
how do you know which value is?
like how do you know is @actor.charactersitcs

**Comment by Saibot393** [comment]
when you have a token selected a you can open the console(F12) and enter `canvas.tokens.controlled[0].actor`, that should give you an overview over all possible attribute paths available in the roll formulas

**Comment by warhammering** [comment]
ok, I will try that. Seems it was the s and is working but I don't understand the roll. Could you explain it for me

I have the formula and I added the modifer of -30 to break
For example in this one I got a -26
![image](https://github.com/Saibot393/LocknKey/assets/140810683/1bd4d798-e4b2-4464-b183-ff28a41ce6c4)
and in this one I got a 40
![image](https://github.com/Saibot393/LocknKey/assets/140810683/b1836657-2f2a-4ab4-af29-cd1271bc301e)
but I still don't understand how it comes to this numbers

**Comment by Saibot393** [comment]
In this specific casees Lock and Key will do the following:
- A d100 is rolled resulting in a 4(case 1) or a 70(case 2)
- It will subtract the 30 from the results
- It will compare these results to the Locks DC (where result <= Lock DC is a success)

**Comment by warhammering** [comment]
OK, do you think it would be possible to see the roll result of the d100?

**Comment by Saibot393** [comment]
You can already see the specific dice result when you click on the result itself:
![image](https://github.com/Saibot393/LocknKey/assets/137942782/64f8914f-05df-4d0c-a933-3d174bc57f7a)

**Comment by warhammering** [comment]
Oh, that was useful! Thx you so much!

**Comment by Saibot393** [comment]
I have just released v1.11.5 wich adds the option d10 crit limit to the token settings
