### ISSUE TITLE
Break lock does not work with Item piles tokens

### ISSUE THREAD

**Issue by Hevkalo1** [Saibot393/LocknKey#39]
System : pf1 v.9.4
Foundry v 11.313
modules : Item piles 2.7.16 , LocknKey 1.10.7

What's wrong : Every time character roll success for breaking the lock on "item piles" chest message pop up says " Lock is already been opened" but if you try intercating - it still be locked.

Additional info :
 Locks and passwords work fine, you can break doors just fine.

**Comment by Saibot393** [comment]
Thanks for informing me, i will have a look at it.

**Comment by Saibot393** [comment]
This bug should be resolved with v1.10.8
