### ISSUE TITLE
Incorrectly calculating lockpick roll formula in Starfinder

### ISSUE THREAD

**Issue by jxj5034** [Saibot393/LocknKey#43]
This is for the Starfinder (sfrpg) system
For the "Lockpick roll formula" and "Break lock formula", the module does not seem to read skill modifiers from the character sheet.
For reference: the lockpick formula is typically an Engineering check which is 1d20 + the character's engineering skill.

If you enter `1d20 + @skills.eng.mod` in the "lockpick roll formula" field, `@skills.eng.mod` always returns zero. This means every lockpick check is a flat 1d20 +0 and not intended behavior.
This is the same for breaking the lock `1d20 + @skills.ath.mod` where `@skills.ath.mod` also returns zero.

Changing the lockpick formula field to add flat modifiers such as `1d20+2` works as expected but this does not pull any information from the character sheet so is not very useful.

Foundry Version 11
Build 313
Starfinder 0.25.2
I have tried disabling all modules except Lock and Key, with the same behavior.
Currently installed modules:

- Animation Preview
- Auto-rotate
- Automated Animations
- Cosmic Dice
- Dice So Nice
- Dungeon Draw
- Global Progress Clocks
- Grid Scaler
- Health Estimate
- Hephaistos Importer
- Item Piles
- JB2A
- Jinker's Animated Art Pack
- lib-color settings
- libWrapper
- Lock & Key
- Moulinette Core
- Moulinette Game icons
- Moulinette Image Search
- Moulinette Scenes 
- Moulinette Sounds
- Moulinette Tiles
- Nachrtose Scifi Pack
- NameForge
- Polyglot
- quick insert
- Roll Tracker
- Sequencer
- SFRPG Encountergen
- socketlib
- Splatter
- Starfinder Statblock parser

**Comment by Saibot393** [comment]
Lock & Key uses a slightly more general path for skill modifiers, instead of e.g. `@skills.eng.mod` this should work: `actor.system.skills.eng.mod`

**Comment by jxj5034** [comment]
I just tested the formulas above, and your change works! Thank you for the quick reply, I've been pulling my hair out over this.

**Comment by jxj5034** [comment]
One final note:
In starfinder, the formula to lockpick a door should be: `1d20 + @actor.system.skills.eng.mod` 
Dexterity is not included but the important part was getting the file paths correct which you provided and I am very grateful.
Notably, there is also no 'general' formula for breaking a lock in starfinder.
Thanks again!

**Comment by Saibot393** [comment]
Thanks for the correction, its been a while since i last played Starfinder. I will include the formulas as default in the next version.
