### ISSUE TITLE
[Bug] MATT Compatibility Display

### ISSUE THREAD

**Issue by Crowguard** [Saibot393/LocknKey#44]
![image](https://github.com/Saibot393/LocknKey/assets/99844555/9ef90a7f-fc1a-41c9-9707-3c6bd66afc8e)

![image](https://github.com/Saibot393/LocknKey/assets/99844555/93c24d16-5843-47f6-9675-f714871cd5d7)

Display seems to be showing the full code instead of labels and is cut-off and hard to read.

MATT 11.11
Lock & Key 1.11.1

**Comment by Saibot393** [comment]
Thanks for notifying me, the translation should now be correctly displayed with the new v1.11.2
