### ISSUE TITLE
System Compatibility: Call of Cthulhu

### ISSUE THREAD

**Issue by Aemeth21** [Saibot393/LocknKey#45]
Hello there! 😊

I've noticed there's already a request for compatibility with the Warhammer system, and I would love to see an adaptation for the Call of Cthulhu (CoC7) system as well. Currently, there are not many modules that are compatible with CoC7, but I must say yours is fantastic!

The module is working fine, but there's a slight difference in lockpicking mechanics for CoC7. From what I've read in the "Warhammer system compatibility" request, it seems quite similar. In CoC7, we use different levels of success (Fail, Regular, Solid, and Extreme), which means I can't just set a fixed number for the lock difficulty class (DC). In this case, it would require a 1d100 roll, compared with the player's skill value. If the roll is equal to or lower than the skill value, the player would succeed.

Is it possible to incorporate this compatibility into your module as well?

**Comment by Saibot393** [comment]
I just had a closer look at the way the system stores the skills and it seems easily compatible with Lock & Key. I will probably implement the DC in a way where the numbers corresponds to the degree of success required (0: normal failure, 1: normal success, 2: hard success,...)

**Comment by Saibot393** [comment]
I have added support for the Call of Cthulhu system with v1.11.3. I have used the Locksmith skill as the default skill for lock picking (`1d100/max(1,@actor.system.skills.Locksmith.value)`) in case you want to replace it with Mechanical Repair the check would look like this `1d100/max(20,@actor.system.skills.Mechanical Repair.value)` (can be replaced per character). I will leave this issue open until i get confirmation that everything works as intended.

**Comment by Aemeth21** [comment]
First of all, thank you for time and dedication on adapting this wonderful module for the Call of Cthulhu system. 😊

The "Break lock" is working fine. When a roll is equal or less than the character strength, the lock is successfully broken.
However, the lockpicking is still acting funny. I've attempted a few things to make it work, such as pasting on the token config. one of your examples to override the lockpick formula and changing the skill required for the lockpicking on the module configuration but it doesn't appear to be resolving the issue. 
The door doesn't unlock, even with an extreme success.
If there is any additional information that I can provide to help on this, please let me know.

**Comment by Saibot393** [comment]
Could you send me a screenshot of the character sheet of the token you tried the lockpicking with, and of the lock & key settings tab of the lock?
Are there any errors in the console (F12) when you attempt to lock pick?

**Comment by Aemeth21** [comment]
Sorry for the delay,  but I have now tested all the options, including the hard and extreme successes, and they all work quite well with the changes I've made. Once again, thank you for adapting the module for the COC7 system. 😊

**Comment by Saibot393** [comment]
Glad to hear that everything works.
