### ISSUE TITLE
System Compatibility: Chronicles of Darkness 2e

### ISSUE THREAD

**Issue by RinVindor** [Saibot393/LocknKey#46]
I'd absolutely love to see this module support Chronicles of Darkness 2e. Most of the module works but some aspects like critical rolls don't function since thats outside of what I can create with formulas. I did get the locks/breaking locks working easily enough 😁 took about 30 minutes of poking around. The other thing I'm not sure how to factor in is the Specialties system the game has. In Chronicles 2e a Speciality just adds an additional 1d10 to the total roll and if you've got multiple that apply then each adds to it. In this instance maybe another data box for modifiers and how much they add to both the lockpick and break formulas? That and the system has an option for 10 again, 9 again and 8 again rolls for special abilities and whatnot that enables you to roll additional dice for every dice that lands on said number.

Thanks for all the hard work you put into these amazing mods Saibot!

**Comment by Saibot393** [comment]
I had a look at the system, could you confirm, that i understand the rules correctly:
- A player rolls a number of d10s euqual to the applicable attribute + the applicable skill (what would be the skills/attributes for lock picking/breaking?)
- Some specialities may add d10s to this pool (could you give me an example here?)
- Every 8,9 or 10 rolled counts as one success
- Every 10 may be rolled again and may potentially add additional successes (which may be rolled again if they are a 10)
- A look would be e.g. picked if the player has successes equal or higher to the DC of the lock

**Comment by Saibot393** [comment]
I have added partial support for the Chronicles of Darkness system with v1.11.3. For now only the success for >=8 and reroll on 10 are included. For the other rules i will need more informations regarding when additional dice may be used or under which conditions rolls of 8 or 9 may be rerolled.

**Comment by RinVindor** [comment]
Its wild how fast you work! So the conditions for when dice are rerolled at 8s and 9s is basically up to the GM/ST who is running the game. There are abilities as well that grant the option to roll on 8s and 9s on a specific thing. I'm honestly not entirely sure how to implement this beyond a popup box? Or a clickable box in the chat that asks if its 8s or 9s for rerolling.

Specialties in these systems (same for World of Darkness 20th Anniversary and World of Darkness 5th edition) are left vague and up to the GM/ST to fill in but they include examples to work from. Due to how the systems are implemented where Specialties aren't an item but just a editable line in each Skill, maybe another entry box that lets you type what grants a bonus to said roll?

In the image below you can see it has separate skills for manual lockpicking versus hacking a passworded or digitally protected door. Speaking of which, are you able to introduce a separate system for hacking (feel free to tell me I'm just asking too much 😂).

![image](https://github.com/Saibot393/LocknKey/assets/12647469/6efae3b5-95bd-43e2-b4c6-87e91573a2ab)

In this image is the item used for said manual lockpicking, it grants a bonus to the dice rolls (which I was able to get working already)

![image](https://github.com/Saibot393/LocknKey/assets/12647469/6de1940c-2000-469e-a30f-b0921e8899e5)

**Comment by Saibot393** [comment]
Depending on how flexible specialities are the on token setting for custom roll formulas may surfice for that. 
Is the rule for 8, 9 or 10 rerolling more of a world, character or check dependent thing? Should it be character dependen,t is there a way to add standard foundry effects to a character? I couldn't find an option in the character sheet.
I will look into a hacking option for one of the next versions.

**Comment by RinVindor** [comment]
The reroll on 8s and 9s is character dependent exclusively in my
experience. If I recall right there is a merit that lets the player reroll
on 8/9

**Comment by Saibot393** [comment]
In this case there might be a way to set the reroll value via an easy effect attribute.

**Comment by Saibot393** [comment]
I have just released v1.11.5 wich adds the option d10 crit limit to the token settings

**Comment by RinVindor** [comment]
You're truly a legend at how fast you work 😂. If you've got a donation
link lemme have it.

Now I just need to find a developer who will create a module for more
vision options 😂

**Comment by Saibot393** [comment]
I am actually currently considering adding something like "vision channels", a way for the gm to make certain token/tiles/doors only visible to certain other tokens or make token/tiles/doors visible through walls for other tokens, to one of my modules. Though this is something that will take quite a bit of time and development. If thats of interest to you i could inform you about it, should i ever manage to implement it.

**Comment by RinVindor** [comment]
Yeah I'd definitely be interested in progress on that! In Chronicles of
Darkness vampires have a vision based on the ability to smell blood and
currently there's no way to implement that. Having it work on tokens AND
objects would be amazing.

**Comment by Saibot393** [comment]
> Its wild how fast you work! So the conditions for when dice are rerolled at 8s and 9s is basically up to the GM/ST who is running the game. There are abilities as well that grant the option to roll on 8s and 9s on a specific thing. I'm honestly not entirely sure how to implement this beyond a popup box? Or a clickable box in the chat that asks if its 8s or 9s for rerolling.
> 
> Specialties in these systems (same for World of Darkness 20th Anniversary and World of Darkness 5th edition) are left vague and up to the GM/ST to fill in but they include examples to work from. Due to how the systems are implemented where Specialties aren't an item but just a editable line in each Skill, maybe another entry box that lets you type what grants a bonus to said roll?
> 
> In the image below you can see it has separate skills for manual lockpicking versus hacking a passworded or digitally protected door. Speaking of which, are you able to introduce a separate system for hacking (feel free to tell me I'm just asking too much 😂).
> 
> ![image](https://user-images.githubusercontent.com/12647469/278747132-6efae3b5-95bd-43e2-b4c6-87e91573a2ab.png)
> 
> In this image is the item used for said manual lockpicking, it grants a bonus to the dice rolls (which I was able to get working already)
> 
> ![image](https://user-images.githubusercontent.com/12647469/278747502-6de1940c-2000-469e-a30f-b0921e8899e5.png)

I have added a third custom way to circumvent locks with v2.0.0 that can be used for thinks like hacking

**Comment by RinVindor** [comment]
Saibot you're a legend, honestly.
