### ISSUE TITLE
[Feature Request] Limit Lock&Key-Tab to "Type of key items"

### ISSUE THREAD

**Issue by gsterling** [Saibot393/LocknKey#47]
I have specified a certain item type for keys, but the tab is still displaying for all items regardless of type. I wish it'd just show the tab for the items of the specified type or even only for created keys instead of everything.

![image](https://github.com/Saibot393/LocknKey/assets/58980630/d433530d-dd11-454a-91a4-01de9ad7b079)

**Comment by Saibot393** [comment]
The tab is also necessary for e.g. lock picks which are not always of the same type as keys, but i can add world setting for a "whitelist" for item types

**Comment by Saibot393** [comment]
I have just released v1.12.0 which adds the world setting Setting item types for this purpose
