### ISSUE TITLE
Lock pick roll + too high

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [Saibot393/LocknKey#48]
Hello. Just brining this up to see if this is user error or some module conflict. When a player uses thieves tools to pick a lock (he is currently level 8 with prof of +3) He is rolling with Dex and +2 and then a +8. I'm sure it's supposed to be 3 due to prof and i am not sure where the +8 is coming from. Loving the mod despite this though, so thank you.

**Comment by Saibot393** [comment]
I am assuming you are using D&D 5e and the normal default Lockpick formula (`1d20 + @actor.system.abilities.dex.mod + @actor.system.tools.thief.total`)? 

Iif so, could you send me:
- A screenshot of the Lock & Key chat message containing the roll result for the pick lock interaction
- The output when having a token selected and entering `canvas.tokens.controlled[0].actor.system.abilities.dex.mod + canvas.tokens.controlled[0].actor.system.tools.thief.total` into the console(F12)

**Comment by Quinn-Aetherwood** [comment]
I am indeed using (1d20 + @actor.system.abilities.dex.mod + @actor.system.tools.thief.total). Could you screenshot how to get to canvas.tokens.controlled[0].actor.system.abilities.dex.mod + canvas.tokens.controlled[0].actor.system.tools.thief.total? I have pulled up the console but i'm not sure where to go from there.

**Comment by Saibot393** [comment]
At the bottom right of the console/screen there should be a small text field:
![image](https://github.com/Saibot393/LocknKey/assets/137942782/3e703aa7-384e-4d82-b84d-152afec846ad)

**Comment by Quinn-Aetherwood** [comment]
![image](https://github.com/Saibot393/LocknKey/assets/127997499/ee436d62-9ca9-45b5-9012-86390769abb4)

Hmm bottom right i only seem to have this

**Comment by Quinn-Aetherwood** [comment]
Dropping this in though this was the total roll. 
![image](https://github.com/Saibot393/LocknKey/assets/127997499/12691d27-fe73-46d7-b933-b38a4134efc3)

**Comment by Saibot393** [comment]
You should be able click at the white space in between the last console line (Foundry VTT |  [...] foundry.js:3629) and the gray bar with console and issues

**Comment by Quinn-Aetherwood** [comment]
![image](https://github.com/Saibot393/LocknKey/assets/127997499/4f470b65-f6a2-4ffa-ac25-f2f7774f3002)
Sorry, i think i get what you mean. This is what outputs.

**Comment by Saibot393** [comment]
Ok, im am starting to where the problem is, could you now enter `canvas.tokens.controlled[0].actor.system.tools.thief` (again while having the token controlled) and then click at the result to unfold it (it should more or less like the attached screenshot):
![image](https://github.com/Saibot393/LocknKey/assets/137942782/8bfabbc1-d1ba-48e3-97ae-f18d48a638d9)

**Comment by Quinn-Aetherwood** [comment]
![image](https://github.com/Saibot393/LocknKey/assets/127997499/b9c9bd48-7cf8-421e-a658-eb6c8cf6785c)

**Comment by Quinn-Aetherwood** [comment]
He does have expertise with the tools which could account for doubling the prof. However, i tested theives tools on another character that is only proficent and it still gave him a +8 without expertise.

**Comment by Saibot393** [comment]
Yes, the expertise is one part of the problem. A nother one seems to be that i used the the wrong formula. The right formula should be: `1d20 + @actor.system.abilities.dex.mod + @actor.system.tools.thief.value * @actor.system.attributes.prof`

**Comment by Quinn-Aetherwood** [comment]
Here are the values of prof only, not expertise character. 
![image](https://github.com/Saibot393/LocknKey/assets/127997499/d0560b58-66ce-4bc1-a221-94133fa1580d)

**Comment by Quinn-Aetherwood** [comment]
That's ok mate. No harm no foul, just thought i would bring it to attention.  Is part of the problem is it's adding INT into the mix? It's supposed to be DEX + PROF, right?

**Comment by Saibot393** [comment]
Right, Lock & Key ignores the ability modifier setting though to make sure that dex is always rolled

**Comment by Quinn-Aetherwood** [comment]
Gotcha. Should i change this setting manually in the formula or is this an update fix for the future?

**Comment by Saibot393** [comment]
You will have to change that manually, updates won't change formalus to not destroy custom setups (i will include a formula update macro in the next update though). Here is an improved formula for Lock picking:
`1d20 + @actor.system.abilities.dex.mod + @actor.system.tools.thief.prof.flat + @actor.system.tools.thief.bonus`
And for Lock breaking:
`1d20 + @actor.system.abilities.str.mod + @actor.system.skills.ath.prof.flat`

**Comment by Saibot393** [comment]
The new v1.12.1 updates the formulas and includes a macro to atomatically update to the new formuals.

**Comment by Quinn-Aetherwood** [comment]
Awesome. Thanks Saibot.
