### ISSUE TITLE
[REQUEST] Default Key Folder

### ISSUE THREAD

**Issue by maxobremer** [Saibot393/LocknKey#49]
It would be nice if you could set a default folder for any newly made keys. I got quite a few folders in my items directory and it would be nice if it automatically have the key folder selected.

In addition it would be nice if you could have a default folder that also limits the folders you search for. What i mean with that is that in the settings you would define a folder as the main one and when you make a key it would either be placed there or you can search for other folders, but only those within the main key folder. That way you dont have to go through all the folders in your item directory, which can be a slog.

thanks for the nice module so far btw

**Comment by Saibot393** [comment]
Thats a good idea, i will include it in the next version

**Comment by Saibot393** [comment]
I have added setting for the default folder with v2.0.0
