### ISSUE TITLE
[REQUEST] Set default Pick and Break DC

### ISSUE THREAD

**Issue by maxobremer** [Saibot393/LocknKey#51]
It would be nice if you could set the default DC for picking the lock or breaking the lock. That way it would save time when you quickly need to lock a door you forgot during a session and just in general makes life easier.

In addition it would be nice if the two default DCs can be different values, seems obvious but felt like i should mention it anyway.

**Comment by Saibot393** [comment]
I will include it in the next version

**Comment by Saibot393** [comment]
World settings for the default DCs have been added with v2.0.0
