### ISSUE TITLE
Menu bug?

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/LocknKey#53]
I noticed that when I use the key menu for the players, the first option (LockuseFree) is not showing as it should?
![Capture d'écran 2023-11-05 232740](https://github.com/Saibot393/LocknKey/assets/149971487/3c539173-8bb1-4b14-abc5-dbf258673b8f)
Maybe i'm doing something wrong?

**Comment by Saibot393** [comment]
I forgot the string in the translation files. I will quickly add it. If you want you can send me the french string, i will include it then

**Comment by MastaGooz** [comment]
Ok cool ! The fr string should be ''déverrouillage gratuit'' then

**Comment by Saibot393** [comment]
The new v1.12.4 includes the missing string. Thanks for providing the french version
