### ISSUE TITLE
GM "alt + right-lick" shortcut locking actors that should not be lockable

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/LocknKey#55]
Sorry, it's me again !
As a GM, when I use 'Alt + Right Click' on actors that shouldn't be lockable (like players, NPCs, etc.), they become locked and behave like locks : neither I nor the players can access their sheets anymore and right-clicking on them open the popup menu.

**Comment by Saibot393** [comment]
I will llok into it, thanks for informing me

**Comment by Saibot393** [comment]
The tokens should still be unlockable by alt+right-clicking them again, right?

**Comment by Saibot393** [comment]
The bug should be fixed with v1.12.6, now alt+right-clicking will only work with compatible tokens

**Comment by MastaGooz** [comment]
Yes, tokens should still be unlockable by alt+right-clicking them, and thanks it works perfectly !
