### ISSUE TITLE
[Error] Default Token Settings

### ISSUE THREAD

**Issue by Crowguard** [Saibot393/LocknKey#56]
Occurs when accessing the default token configuration settings.

https://github.com/Saibot393/LocknKey/assets/99844555/3afdf4c0-3c18-4a20-8f16-e0ceb95a7467

![image](https://github.com/Saibot393/LocknKey/assets/99844555/8eec5574-caeb-42f9-93e3-d579eac963b1)

Foundry 11.314
PF2 5.8.2
Lock & Key 1.12.6 (video shows 1.12.1, confirmed its still an issue afterwards)

**Comment by Saibot393** [comment]
Thanks for reporting the error, should be fixed with v1.12.7
