### ISSUE TITLE
Custom action floating text bug

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/LocknKey#58]
Hey, it's me again... sorry !

I found a bug : when I use the custom option to unlock a door and I fail, the floating text is not showing what it should. 
I got : "LocknKey.Popup.checkfailed"

**Comment by Saibot393** [comment]
Thanks for notifying me, i forgot the translation. Should be fixed with v2.0.6

**Comment by MastaGooz** [comment]
Thanks !

Fr translation is : "{pCheckName} a echoué"

**Comment by Saibot393** [comment]
Thank you, i have included the translation string in v2.0.7
