### ISSUE TITLE
 [BUG] Every lock is out of reach, even when their not.

### ISSUE THREAD

**Issue by SamuraiPizzaCat420** [Saibot393/LocknKey#59]
pretty much what the description says. the symptoms are...

It can detect how far you are by not  stating "lock is out of reach" when im actually out of reach

when im in reach all the click commands come out with the "lock is out of reach" instead of their respective things. 

messing with the distance to open also doesn't do anything

the problem extends to pretty much anything. 

Ive tried uninstalling and reinstalling the module and creating new actors to lock but everything is the same. This caused much embarrassment when one player tried to pick this chest he been on for 3 sessions. Plz help!

**Comment by Saibot393** [comment]
Did you have multiple tokens selected while trying to interact with a lock?
Do you use Lock & Keys interaction distance or Arms Reachs?
What is your interaction distance set to and what is your scenes Grid scale Distance set to?

**Comment by SamuraiPizzaCat420** [comment]
No :( I logged into a player instance for the test and only had control of him. 
I don't have Arms Reach.
I tried at 1,2....by god 5 did it. I'm guessing because im using the dnd5e standard 5ft it needed 5 units to work. It used to work with 1... i swear lol. I double checked too, anything under 5 wont work. its still outta reach. I think this fixes it. Thank you so much for the rundown!
