### ISSUE TITLE
Bug - None lockable tokens still show out of reach message and can be force broken

### ISSUE THREAD

**Issue by diwako** [Saibot393/LocknKey#6]
As title said.
If a player right clicks a token out of reach which is not an Item Piles container the text will show up that the token is out of reach.
When in range of the token, right clicking will do nothing, no pop up and nothing happens. (correct behavior)
Alt+Right click on token will either say it is out of reach when not in range or will still attempt to break the lock which does not exist.
Attempting to lock pick a token which is not lockable will also display the text, either out of reach or in reach.

**Comment by Saibot393** [comment]
Thanks for letting me know. I will fix this behaviour in the next version (v1.4.0) which will probably be released later today or tomorrow.

**Comment by Saibot393** [comment]
The bug should now be fixed with v1.4.0
