### ISSUE TITLE
Actors behaving like locks when they should not

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/LocknKey#60]
I'm getting the old bug sometimes, when actors start behave like locks (opening popup menu on right click and try to open on left click).
It's not consistent and I can't really tell what is making this happen, but when it does, I have to delete the token (reload won't change anything) and drag the actor in the scene to fix it. 

I wish I could tell you more so you can reproduce it but it just happen randomly or I didn't get the pattern yet.

**Comment by Saibot393** [comment]
I will look into it.

**Comment by Saibot393** [comment]
Assuming the "Show all lock interactions" setting is turned off, which interaction options show up in the popup menu?

**Comment by MastaGooz** [comment]
I'll tell as soon as I get the bug again

**Comment by MastaGooz** [comment]
It seems like when "Show all lock interactions" setting is turned off, the popup menu is not showing up at all, but when I left clic on the actor, it acts as a lock "Actor is locked", and playing the lock sound.

**Comment by Saibot393** [comment]
Could you enter this `canvas.tokens.controlled[0].document.flags.LocknKey' into the console(F12) while having the token in question selected and send me a screenshot of the result?

**Comment by MastaGooz** [comment]
Sure, as soon as the bug is back i'll do it.

**Comment by MastaGooz** [comment]
Having disabled the "show everything" on the popup option, I don't see the bug anymore (at least for now).

**Comment by MastaGooz** [comment]
Yes, it seems like the popup menu "show all" could be the problem.

**Comment by Saibot393** [comment]
That narrows down to possible causes, i will look into it

**Comment by Saibot393** [comment]
I have looked further into the issue, is it possible, that the token(s) to which the bug applies were locked when the previous bug allowed some unintended tokens to be locked and never unlocked again?

**Comment by MastaGooz** [comment]
I'll put the option back on and try with fresh tokens

**Comment by MastaGooz** [comment]
I'm not seeing any bug so far so you're probably right ! If I find anything i'll let you know

**Comment by Saibot393** [comment]
I will write a macro that will remove the faulty data from the invalid prototype tokens, just to make sure

**Comment by Saibot393** [comment]
I have added debug/clean up code with v2.0.8. The code should remove faulty data entries from all prototype tokens. You can execute the code by either typing `game.modules.get("LocknKey").api.CheckActorPTokensCompatibility()` into the console or executing it as a macro. Make sure that Item Piles is active during that, since the debug code will not recognize item piles actors/tokens as compatible otherwise

**Comment by MastaGooz** [comment]
Perfect, thanks man.

**Comment by Saibot393** [comment]
For now the problem should be counteracted by using the "Always open owned" word setting. Could you send me the console output when having one of this bugged tokens selected and entering `canvas.tokens.controlled[0].document.flags.LocknKey` into the console? Also, are you using rideable and if so, do you have the rideable-lock & key integration activated?

**Comment by MastaGooz** [comment]
Yes, the "always open owned" resolved the issue (idk why I didn't do that before).

![image](https://github.com/Saibot393/LocknKey/assets/149971487/41a3dae2-45c9-424c-aaba-a9700b75a31f)

Yes, I use rideable and I have the rideable-lock & key integration activated. But my token is not "ridable" and I tried turning off ridable (and the integration) but the bug is still there.

**Comment by Saibot393** [comment]
I have fixed a small error with v2.1.1 that may have been responsible for this behaviour.

**Comment by MastaGooz** [comment]
So, when testing rideable, I found out about this bug ! It was not really a but, actually the actor of the token must have been a pile or a rideable BEFORE (and set as locked) then been back to not rideable + not a pile, but stayed locked (and the setting to lock/unlock was not available anymore since its not a rideable nor a pile)... I fixed it by puting it as rideable, unlocking then puting it back as non rideable.

Do I make sens?

**Comment by Saibot393** [comment]
That makes sense, would explain all the strangeness surrounding this behaviour. I will think about a way to prevent this from happening in the future.

**Comment by MastaGooz** [comment]
Yes, I should have figured this out before... But I dont remember locking the acotr that way (but I was testing so much that it's possible). I'll let you know if I find something else but I don't think so.

**Comment by Saibot393** [comment]
Are there still problems related to this issue or is everything solved? If so i would close this issue.
