### ISSUE TITLE
Arms Reach compatibiliy issue?

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/LocknKey#61]
Sometimes (I don't know why again, not founding the pattern), I can't acces actor's sheets with double left click anymore and I have to reload to be able to open them again (with double click).

When it's happening, I get this in the console : 
![image](https://github.com/Saibot393/LocknKey/assets/149971487/17802f04-3ec8-414b-a509-1b7b51143e8d)

I thought it was Arms Reach but when I turn LocknKey off, it don't happen anymore.

**Comment by Saibot393** [comment]
I've had a look at the arms reach source code, i think that this is an arms reach bug that simply gets triggered more often when lock & key is active, i will create a PR for arms reach to fix this.

**Comment by Saibot393** [comment]
The issue should be solved with arms reach v2.3.5

**Comment by MastaGooz** [comment]
Ok, i'll test it, thanks man

**Comment by MastaGooz** [comment]
I think the bug is gone indeed. Nice work man.

**Comment by Saibot393** [comment]
Good to hear
