### ISSUE TITLE
[Enhancement] Proper images for essential L&K macros :)

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/LocknKey#63]
I realize this isn't the most urgent request. But it would be nice to have proper themed images for the Pick Lock and Break Lock macros.

Also, Saibot, are you on the Pathfinder Discord at all? I feel like your Perceptive and Lock and Key mods should have their own dedicated threads in the modules channel there (alongside Workbench, Dorako, etc.). Would be a nice way to field user questions about your modules, which are superb but which also do a lot that I don't always understand. ;) And also spread the word about them. I don't think folks realize just how much your mods can do.

**Comment by Saibot393** [comment]
Good idea, i will look through the default foundry icons and see if there is anything appropriate.

I am on the Pathfinder server from time to time to see if there are any mentions related to my modules. I wasn't sure if my modules were relevant enough to be listed in there, nor whom to contact about that.

**Comment by weepingminotaur** [comment]
Oh yeah, it's true your modules aren't Pf2e-specific. But if you're on that Discord sometimes, I might ping you on the general module channel then if I have questions, so I don't have to bother you on the github. And hopefully draw more attention to your modules in the process, because they're great!

**Comment by Saibot393** [comment]
Glad you enjoy them

**Comment by Saibot393** [comment]
I have added icons for some of the Lock & Key macrocs (Break/Pick Lock, Pick Pocket, Use custom check, Use Key...) with v2. 0.11. A similar update for both Perceptive and Rideable will follow shortly.
