### ISSUE TITLE
[Display Issue] L&K tab causes white space

### ISSUE THREAD

**Issue by weepingminotaur** [Saibot393/LocknKey#65]
<img width="652" alt="Screenshot 2023-11-28 at 4 23 03 PM" src="https://github.com/Saibot393/LocknKey/assets/90105219/7699ba31-a3d7-4102-90eb-69b3b8c00d9c">

Solution: maybe no line break? But also an acronym instead of the full name (L&K or maybe a lock emoji?).

**Comment by Saibot393** [comment]
The line break isactually automatically inserted by foundry, using L&K sound like a good idea

**Comment by Saibot393** [comment]
I have shortened the tab button text to "L&K" with v2.0.12
