### ISSUE TITLE
Feature Request: Add option that allows player to locking a door with a password

### ISSUE THREAD

**Issue by p4535992** [Saibot393/LocknKey#66]
It would basically be the feature already present of locking doors based on key items, but without items and only with a dialog to set the password.

**Comment by p4535992** [comment]
@Saibot393 sorry i must be very stupid, i cannot find this feature , what did you mean with "only useable with the popup-menu control sceme" ?

**Comment by p4535992** [comment]
A nevermind i found it!.

Two things:
1) Add a check for avoid the new passwrod to be empty (because it will convert to a standard key behaviour)
2) It is possible to add a additional key binding for set the new password without the player go to set the module setting ?

**Comment by Saibot393** [comment]
I currently don't have a kofi link (or somilar). Not sure if i will ever make one/add one to the project.

**Comment by p4535992** [comment]
sorry to bother again...people who had difficulty setting module settings have difficulty setting keybinding...can you put a default value on the "Change Password" key binding ? (also for the "pick pocket" if that is not a problem)

**Comment by p4535992** [comment]
Ty really appreciate  this.
