### ISSUE TITLE
GM control not showing in settings

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/LocknKey#69]
![image](https://github.com/Saibot393/LocknKey/assets/149971487/1a4ed214-7e78-45ec-af2a-550bc3b5dc51)

As you can see in the screenshot, I don't see any GM controls showing up in the settings (but the players controls are showing).
I tried in english to verify that I didnt to anything wrong with translation but it's the same.

"GMControls" : {
				"line0"					: "Contrôles du MJ:",
				"line1" 				: "•shift+right-click pour créer une nouvelle clé",
				"line2" 				: "•alt+right-click pour activer le verrou d'un jeton (*)",
				"line3" 				: "•ctrl+right-click pour copier les IDs des clés du verrou (*)",
				"line4" 				: "•ctrl+left-click pour coller les IDs des clés dans le verrou (*)"
			},

**Comment by Saibot393** [comment]
The GM controls should now appear again with v2.2.4.
Regarding the pick pocket feature, which system are you using?

**Comment by MastaGooz** [comment]
Custom System Builder

**Comment by Saibot393** [comment]
what is your worlds pick pocket formula set to?

**Comment by Saibot393** [comment]
Yes, that was a bug. Should be fixed with the new v2.2.5, sorry for that

**Comment by MastaGooz** [comment]
Awesome man, thanks !
