### ISSUE TITLE
[Bug] Lockpicking attempt freezes the game

### ISSUE THREAD

**Issue by cadowtin** [Saibot393/LocknKey#7]
^^

On a door where i edditted properties to have a key, and then set a certain amt of lock picking opportunities

**Comment by Saibot393** [comment]
Which game system are you using? Also, could you attach a screenshot of the doors setting and the lockpicking characters inventory?

**Comment by Saibot393** [comment]
Also, do either the Lockpicking dice roll or the "attempt failed/succeeded"message show up in the chat before the game freezes?

**Comment by Saibot393** [comment]
I think the bug should be fixed with v1.4.1.

**Comment by cadowtin** [comment]
It seems to not happen anymore, unsure what was causing it, but going to close for now unless it shows up again!
