### ISSUE TITLE
Lock & Key + Item Pile in CSB

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/LocknKey#70]
Hey,

I'm trying to make Lock & Key work with Item pile in CSB (since Item Pile just got patched to work in CSB, wich is awesome).

I found some things that do not work as expected in the pickpocket feat : 

- money is not working at all (I can see the money in the pickpocket popup, but when I try to take it, nothing change in both tokens). But on the Item Pile side everything is working fine around money outside of peackpocket (custom money settings of Item Pile, like in the first screenshot).
![image](https://github.com/Saibot393/LocknKey/assets/149971487/93232fb8-9fd8-415e-bce1-56065ecc0639)

- regarding items, I can take them but there is 2 issues :
          1 - Item that are taken during pickpocket and fall to 0 quantity does not disapear form inventory (but the quantity is 0, quantity is 
             set up in Item Pile custom quantity, like in the 2nd screenshot).
![image](https://github.com/Saibot393/LocknKey/assets/149971487/60c519af-b26a-41a1-9fb7-7fce153e7962)

          2 -  When a token peackpocket an item that is already existing in his inventory, an other pile is created instead of stacking on the 
            already existing item (like Item Pile does since the patch).
            
I don't know if those features are expected in your module (if not feel free to ignore this), but since it's supposed to be compatible with Item Pile I tested it.

Btw, I also have a question about the peackpocket setting, I don't understand the last 3 settings (last screenshot), what is this supposed to do exactly? Is it a DnD5 only feat? I can't test it because I don't understand the mecanism.
![image](https://github.com/Saibot393/LocknKey/assets/149971487/125d0b6a-9539-482e-8553-6d9414cf2b15)

Sorry for being such a pain man 😭 

Also, i'll translate all your modules in FR soon to make it up

**Comment by Saibot393** [comment]
1. I will look into, ist that still the same CSB world file you send me last time?
2. That is currently intended (more or less) intended. It is basically a safety feature to not accidentally delete or overwrite item data (both the item at 0 remaining and the not stacking)
3. The last three options are there to allow for a dynamic Pick Pocket DC. In D&D5e for example, these settings would allow for the use of passive perception as the default pick pocket DC (1. setting) or active perception checks to increase/update the Pick Pocket DC (2. and 3. setting)

Don't worry about all the questions, i am happy to answer them

**Comment by MastaGooz** [comment]
Thanks for your answer,

Yes, it's the same CSB world, I'm doing a bunch of testing of various modules on it.

So, if I understood correctly, the pickpocket DC formula is "based" on the victim's attributes? Like if I try to stole a token with a variable named "paranoia" (=15) then the DC would be 15+ ? And I could use the formula @system.props.paranoia to refer this attribute (in CSB, attributes are stored with the system.props.X path)?

And then, if I want to formula to be dynamic (so every try is based on a new check), then I check the option "auto update" and I put a perception key word? Then everytime a pickpocket is tried, the roll associated with the key word will be rolled? 

Does the roll need to be an inline roll in the character sheet? Or could it be a macro as long as the flavour is containing the key word?

**Comment by Saibot393** [comment]
Yes, thats correct, the first formula is passiv and the keyword is the active part. Every roll that has an ouput in the chat containg the keyword should work. The module also includes a macro to reset tokens pick pocket dc to the default passive/formula calculated value, in case you want to use both methods at the same time.

**Comment by MastaGooz** [comment]
There is no limit in the peackpocket max try (like in the lockpicking action)? Because if I have a player that try to stole a token and fail because the perception check is a succes, nohting is preventing him to spam it right?

**Comment by Saibot393** [comment]
Currently not, but i can add a limit similar to the lock pick attempts.

**Comment by MastaGooz** [comment]
I think that could be a nice feat indeed.

So I tried again the peack pocket thing, but it seems that whatever I put in the "peack pocker default DC formula" is not being used at all nor whatever I put in the "classic" default peack pocker difficulty. When I create a new token/actor, the default is always -1 (in the token settings), and that value is always the one that is take in consideration for what I saw (changing this value is what actually is take in acount).

**Comment by Saibot393** [comment]
Are there any errors in the console when opening the settings sheet of a new actor for the first time? Does the "Reset Pick Pocket DC (selected or scene wide)" macro reset the values correctly?

**Comment by Saibot393** [comment]
Also, what is the formula you used for pick pocket dc?

**Comment by MastaGooz** [comment]
My PP formula is : 1d20 + @actor.system.props.Escamotage + @actor.system.props.AGI_mod (1d20 + dex mod + pick pocket mastery), and it works fine.

Then the set up is : 
![image](https://github.com/Saibot393/LocknKey/assets/149971487/2af34acd-17a8-426a-a777-449ea6be1808)
(using dex mod as the check)

But I always get this in the token : 
![image](https://github.com/Saibot393/LocknKey/assets/149971487/d5424596-51ac-4249-86f1-0266bdd7c1c1)

I have nothing in the console. I tested this without any other modules.

**Comment by Saibot393** [comment]
I tried to replicate the two bugs (money not transferring and the DC not being calculated correctly) with the actor export you send me last month. 
This version of the character only has currencies so i tried to base the DC on the currencie and it seemed to work. Did you try to use the reset macro? There is achance, that the -1 value was set previously as the explicit value and is therefore not overwritten by the default formula/value. 
Regarding the problem with looting money, was that with an item pile token? In this case, could you send me money data path of such an token/actor (type `canvas.tokens.controlled[0].actor.system.props` into the console while controlling the token)
Could you send me an up to date export of the actor type for further testing?

**Comment by MastaGooz** [comment]
No I forgot to try the macro, mb, I'll test it.

About the looting money issue, it was not an item pile ''pile''. It was a classic token acot (NPC like). But I got the issue with both anyway (pile and classic token). 

I'll send you the data path and an the actor asap.

**Comment by Saibot393** [comment]
I think to properly fix this/figure this out, i will need your world file (just the "raw" data without pictures, sounds...)

**Comment by MastaGooz** [comment]
I'll try to make it in a fresh world with minimum settings to check and then I'll give it to you

**Comment by MastaGooz** [comment]
I just tried in a new fresh CSB world and it works fine... currency + difficulty settings... I don't understand why that does not work in my main world... I need more testing to understand...

**Comment by MastaGooz** [comment]
So.... I deleted and recreated actors and token from scratch in my main CSB world and the pick pocket money is working fine... I have NO idea why in my old actors those weird bugs were happening. But I tested so many stuff that maybe I fucked up the settings.

I'm sorry that I made you lose your time over my own mistake...

Regarding the difficulty setting (DC formula), I can't get it to work in my main world (tried both macro) but it work fine in the fresh world, wich I don't know... I tested in without any other module buf still not taking the DC formula settings (even the classic default pick pocket formula is not taken). I'll try to find out.

I'll let you know if I find the origin of the bug, must most likely it's a problem, not your module, again i'm sorry for that. I should have check this deeper before opening the issue.

**Comment by Saibot393** [comment]
Don't worry, narrowing down the problem, especially in a modular system, is hard. Let me know if i can be of any help.

**Comment by MastaGooz** [comment]
Ok I find where the problem is : 

When I use the item pile macro to convert a token into a lootable : 

if (!canvas.tokens.controlled.length) return;
game.itempiles.API.turnTokensIntoItemPiles(canvas.tokens.controlled)

And then I turn it back to a regular token with : 

if (!canvas.tokens.controlled.length) return;
game.itempiles.API.revertTokensFromItemPiles(canvas.tokens.controlled)

THEN, the token si considered as "lockable" for ever, and right clic + shift on it will open the key making window AND lock the token (even if you don't create a key). Also the "lockable" and "locked" options keep to show up in the token settings (even if it's not a ridable nor a lootable).

I tried multiple ways and only the macro causes this issue. If I turn on and off the lootable via token settings of item pile, there is no issue.

**Comment by Saibot393** [comment]
I will look into it, at least the problem with the settings should be easy enought to fix. Part of it sounds though, like it may be a item pile issue, in which case i  will try o see if i can fix it via PR.

**Comment by Saibot393** [comment]
The bugs you described should now be fixed with v2.3.3.
Thank you for your detailed description of the bug, that was very helpfull in fixing it. Also, thank you for your patience, sorry that it took so long.

**Comment by MastaGooz** [comment]
Np, thanks for fixing all this so fast. And thanks for your amazing modules.

**Comment by Saibot393** [comment]
Just to make sure, i think this issue should be resolved, right? Or did i miss something? Otherwise i would close it.
