### ISSUE TITLE
Custom pop ups

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [Saibot393/LocknKey#73]
Hello. At the moment, custom pop ups don't seem to trigger when interacted with a door. If i add a custom pop up like "door cannot be picked" That door will no longer be able to be interacted with, using a lock pick. So no pop up shows up but also nothing rolls with the lock pick either.  Have i got something setup wrong?
![image](https://github.com/Saibot393/LocknKey/assets/127997499/115ab5bb-e864-4013-bcad-0550ff2aa99d)

**Comment by Saibot393** [comment]
I have tested a bit and everything seems to work as expected for me.
Are there any errors in the console(F12) when interacting with such a lock?
Could you send me screenshot of both the locks L&K settings tab and the locks custom popups window?

**Comment by Quinn-Aetherwood** [comment]
Tried K. Didn't see any pop ups come up. The only pop up that seems to work is on another door i have which requires a password which the door prompts on right click. Other than that i can't seem to get any other custom pop up to work like can't be broken, door is locked, etc.

**Comment by Quinn-Aetherwood** [comment]
One thing i noticed i don't seem to have compared to Bailey wikis video is i don't have GM controls in my menu options. Screenshot below 
![image](https://github.com/Saibot393/LocknKey/assets/127997499/910569b5-90a5-4c52-9a8e-cdadff59f5a9)

**Comment by Saibot393** [comment]
Do you have the wold setting "Scrolling status text" activated?

**Comment by Quinn-Aetherwood** [comment]
I didn't have it on, i just tested it with it on an unfortuntely still no text popups available.

**Comment by Saibot393** [comment]
Could you try executing this line `canvas.interface.createScrollingText(canvas.mousePosition, "Test", {anchor: CONST.TEXT_ANCHOR_POINTS.TOP, fill: "#FFFFFF", stroke: "#000000"})` in the console while having your mouse in the canvas and see if any text pops up?

**Comment by Quinn-Aetherwood** [comment]
No text comes up on canvas after entering that into console.

**Comment by Saibot393** [comment]
Then the problem is probably not directly Lock & Key related, since that code is core foundry.
Could you try disabling all modules and using the line above again?

**Comment by Quinn-Aetherwood** [comment]
Ok, all modules off and test showed up. So one of my modules for some reason is blocking text?

**Comment by Saibot393** [comment]
That appears to be the case, i would recommend using [Find the culprit](https://foundryvtt.com/packages/find-the-culprit/) and reusing the code line above to test the iterations. Once you find it you can open an issue on that modules page, though, out of curiosity, i would ask you to also let me which module it was

**Comment by Quinn-Aetherwood** [comment]
Sure thing, doing that right now. I'll let you know once i have found it. Thanks for the help, mate.

**Comment by Saibot393** [comment]
Thats interesting, good to know.

**Comment by Quinn-Aetherwood** [comment]
Just tested out your module without RPG damage numbers. Everything is working as intended. Scrolling messages and the custom pop up box all working. I have submitted a bug report in Rippers discord group.

**Comment by Saibot393** [comment]
Thats good to hear.
