### ISSUE TITLE
Feature: Tidy 5e Rewrite Compatibility

### ISSUE THREAD

**Issue by kgar** [Saibot393/LocknKey#75]
I am the author of the Tidy 5e rewrite. We have some mutual users who are big fans of Lock & Key and the new rewritten sheets, so I would like to discuss some options for establishing compatibility. Because it runs on different web tech than usual, using svelte and fine-grained reactivity, compatibility requires a slightly different approach from the conventional handlebars / form application approach.

I have created a Tab Registration API as part of the integration APIs for Tidy 5e sheets, and in the case of Lock n Key, there is an [Item sheet tab registration API function](https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/Tidy5eSheetsApi.html#registerItemTab). The sheets are currently able to take HTML tabs, Handlebars tabs, and svelte tabs. Technically, we could take vue, react, etc., tabs, depending on their methods and options for mounting elements in the DOM. When registering HTML and Handlebars tabs, the API will use a default configuration of re-rendering tab contents in the Handlebars lifecycle. That is, it will clear the markup and re-render it all on each call to the form's render function.

Mainly, I wanted to get the conversation started and see if you were interested in integrating with my sheets and to be available in you have any questions.

Thank you for reading. I hope to hear your thoughts on this.

**Comment by Saibot393** [comment]
I am definitely interested in making the modules compatibil, thanks for reaching out.
I will play around with the api later and see whats necessary to make the tab work.

**Comment by kgar** [comment]
That's awesome. Our mutual users will be very happy! 🎉
If I am missing any default-sheet-compatible CSS for your tab, let me know and send me some sample HTML, and I'll get that added in.
I have been gradually adding on CSS that provides the Tidy-ified version of default sheet HTML/class structures.

**Comment by Saibot393** [comment]
I have just released v2.4.4, adding the Lock & Key settings tab to Tidy 5e item sheets. I will leave this issue open for now in case i missed something.

**Comment by kgar** [comment]
Thank you very much! I've had at least one user test it out and confirm it to be working.

It means a lot that you'd apply some intentional compatibility with the new sheets. I greatly appreciate it.

**Comment by Saibot393** [comment]
One question, i tried to join the discord linked on the tidy readme out of curiosity. The link however only leads to a discord error page. Is that because the server is private or is the link broken?

**Comment by kgar** [comment]
The link is broken at this time. I will get it fixed sometime soon.
In the meantime, I will DM you a good link.
