### ISSUE TITLE
Lock and Key Token config HUD issues

### ISSUE THREAD

**Issue by uniwars** [Saibot393/LocknKey#76]
Hi, the module seems to adds unused "triggers" tab in the token config HUD, as well as making it look weird

Here is without the module enabled :
![image](https://github.com/Saibot393/LocknKey/assets/65986545/c12f51fb-9daa-455e-9ba5-8dc7d296d25c)

And here with the module :
![image](https://github.com/Saibot393/LocknKey/assets/65986545/45e36852-baad-4c33-802f-f1e850fc4a81)
![image](https://github.com/Saibot393/LocknKey/assets/65986545/996e8928-6667-4678-ab4c-49e859538429)

Since the LK tab has only one setting in it
![image](https://github.com/Saibot393/LocknKey/assets/65986545/9003e5e9-f8d5-4c01-9ece-ab790e1dfd29)
could it also contains the "Triggers" tab in it, or make them both accessible with a button in the "Identity" tab like the Token Flip mdoule does ? 
![image](https://github.com/Saibot393/LocknKey/assets/65986545/5f544d66-9041-4b6a-9dec-8edd9dccb77d)

**Comment by Saibot393** [comment]
The trigger tab should no longer show up in the other tabs with v2.5.1. I will shift the content of the L & K tab into the identity settings with the next update. I will however probably leave the trigger tab as it is to keep it in line with the other MATT settings.

**Comment by Saibot393** [comment]
If only one Lock & Key setting is present it will now be shown in the Identity tab with v2.5.2
