### ISSUE TITLE
Fallout 2d20

### ISSUE THREAD

**Issue by Saibot393** [Saibot393/LocknKey#79]

**Comment by Fardoragh** [comment]
Hello, I'm not sure if this problem has been solved but personally I can't get the locking formula to work on the Fallout 2d20 system. 
Can anyone tell me how to solve this? 

Thanks for your time.

**Comment by Saibot393** [comment]
The Lockpick formula should look something like this: `2d20cs>=(@ actor.system.attributes.per.value + @ skills.Lockpick.system.value)`, thought this will not consider some of the system specific rules. I plan on adding the system crit rules at some point and also a way to select the amount of d20 forthe roll

**Comment by Fardoragh** [comment]
Thank you for your answer but at the moment, this formula resolve only the half of the issue.
The attributes formula work well but the skill formula dont work, see the sreen.
I'm prooving to find the good way but not easy, if you finf this before me please share me the right formula.

Thank you for your time.


![SharedScreenshot 215](https://github.com/Saibot393/LocknKey/assets/167721283/17abd7d9-2c04-4f9a-9628-6933707c2a82)

**Comment by Saibot393** [comment]
are you using a language other than english? If so you might need to change the `Lockpick` part of the formula to the equivalent in your language

**Comment by Fardoragh** [comment]
Oh ! Yes it's correct need to use the correct language to run correctly the formula.
My Bad. 
Thank you in any case to answer me.

**Comment by Saibot393** [comment]
Good to hear
