### ISSUE TITLE
Tidy5e Sheet Module ID Change

### ISSUE THREAD

**Issue by kgar** [Saibot393/LocknKey#81]
Lock & Key references the module ID for tidy5e when integrating with the sheets.
Now that Tidy 5e Sheets has entered beta, the temporary module ID "tidy5e-sheet-kgar" is no longer in use, and now it is using the original "tidy5e-sheet" module ID.

This is a request to change the module ID reference in Lock & Key from "tidy5e-sheet-kgar" to "tidy5e-sheet". This would make Lock & Key compatible with Tidy 5e Sheets 0.11 and above. Currently, in Tidy 5e 0.11, the Lock & Key content is being placed in an odd location on the sheet:

![image](https://github.com/Saibot393/LocknKey/assets/4632129/c4a601f1-b3f3-4cd7-82b1-124340f397b2)
(screenshot from a Tidy user)

I do not anticipate any other module ID changes. This was a unique case, since I had to have the modules live side-by-side for the last several months.

**Comment by Saibot393** [comment]
The new v2.5.4 includes the updates id
