### ISSUE TITLE
AGE Sysem support

### ISSUE THREAD

**Issue by kamil-merdanov** [Saibot393/LocknKey#82]
Hello there and thank you for your module!

I'm stuck at trying to make a working lockpick roll formula. It should be "3d6 + @abilities.int.value", but it always rolls with +0. No matter what actual value the current character has. The same formula works perfectly fine if rolled from chat.

I'am using [AGE System (unofficial)](https://foundryvtt.com/packages/age-system) with a lot of other modules, but I've also tried your module with [The Expanse RPG (AGE)](https://foundryvtt.com/packages/expanse). The formula is a bit different, but the result is the same: works in chat, does not with lockpicking.
FoundryVTT version is 11.308.

![lock-n-key-formula](https://github.com/Saibot393/LocknKey/assets/157103190/e905404f-a86b-41c0-8a30-8285c6904fb2)

**Comment by Saibot393** [comment]
Due to Lock & Key being intended to be as system agnostic as possible some data paths are not available for rolls (though i really should have a look at adding them).
The formula you wrote needs to start at the actor, so it should look like this: `3d6 + @actor.system.abilities.int.value`

**Comment by kamil-merdanov** [comment]
It works! Thank you very much! 

I'm totally new to the JS and Foundry, and when I was trying to determine the correct data path to the particular stat/roll, I've followed two methods described [here](https://foundryvtt.com/article/dice-advanced/). The first one gave me `@abilities.int.value` and the second `@game.system.model.Actor.char.abilities.int.value`. The latter didn't work at all.
