### ISSUE TITLE
Feature Request: Consequences for failing a Pickpocket check

### ISSUE THREAD

**Issue by Stormthirst** [Saibot393/LocknKey#83]
There doesn't seem to be a way to activate a tile in the event of a failed pick pocket. This would be very helpful in creating consequences for the thieves who decide to pick pocket their way to infamy and fortune. Would work the same way as if someone had failed to pick or break a lock, calling a tile with a Landing option for failed pick pocket.

**Comment by Saibot393** [comment]
I will look into adding triggers for pick pocketing

**Comment by Saibot393** [comment]
Pick pocketing can now trigger MATTs with v2.6.0
