### ISSUE TITLE
Default behavior on tiles problematic for scenes entirely composed of tiles

### ISSUE THREAD

**Issue by vvddries** [Saibot393/LocknKey#84]
Lock&Key being enabled by default on tiles leads to annoying behavior on scenes entirely composed out of titles (locked message and sound on every click). To fix it requires disabling L&K features tile per tile on the entire scene. It would be great to have a global setting to set default behavior on tiles. As a workaround, is the current "Setting item types" somehow leveragable to disable the setting for tiles?

**Comment by Saibot393** [comment]
Not, item types only applies to literal items. I will patch in a few ways to remedy this behaviour as soon as possible

**Comment by Saibot393** [comment]
So, i have released v2.7.1, i think the version should prevent most unintended messges and sound. Let me know if should i have missed something.

**Comment by YenBenGrey** [comment]
I had similar behaviour, whenever I clicked on a tile, any tile I got the door open, door closed sound, the default core sound. 

However after seeking out this issue, and updating to 2.7.1 it is fixed. Thank you.

**Comment by vvddries** [comment]
Seems fully fixed. Thanks!
