### ISSUE TITLE
Module compatibility - Libwrapper warn with "Ready Set Roll!"

### ISSUE THREAD

**Issue by Gensokian** [Saibot393/LocknKey#86]
# Description
Whenever a player logs into the VTT they get the error, that LocknKey modify the same functionality.

# Console warn:
```
libWrapper: module Ready Set Roll for D&D5e and module Lock & Key modify the same FoundryVTT functionality and are more likely to conflict.
Detected non-libWrapper wrapping of 'ItemSheet.prototype._onChangeTab' by module ready-set-roll-5e. This will potentially lead to conflicts.
```

# Versions
 - RSR Module: 3.0.14
 - L&K Module 2.7.6
 - dnd5e: 3.1.1
 - Foundry: [11.315]

# Other Modules
Lock & Key
Libwrapper

RSR Issue: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/425

**Comment by Saibot393** [comment]
So, i looked into it and it not something i can solve on my end, this has to be done by Ready set Roll

**Comment by Gensokian** [comment]
Gotcha! Thanks for looking into it!
