### ISSUE TITLE
Enhancement: Hide options in player popup

### ISSUE THREAD

**Issue by mfozz** [Saibot393/LocknKey#87]
It'd be nice to hide options that aren't being used in the player popup, such as identity, password, and free lock use. For my D&D game, I'd just like to show use key, pick lock, and break lock for most of the locked items. 

I think a way to do this would be to not show options that don't have set values. So if I don't set a password, it doesn't show up as an option in the player popup.

**Comment by Saibot393** [comment]
That should already be possible via the setting "Show all lock interactions"

**Comment by mfozz** [comment]
Ugh, yes sorry. I missed that setting.
