### ISSUE TITLE
Cannot Copy Door ID

### ISSUE THREAD

**Issue by hmbaxharm** [Saibot393/LocknKey#89]
I cannot copy a door's ID following the instructions on the Foundry page/GitHub Readme: "To copy a tokens or doors IDs ctrl+right-click them and to paste them ctrl+left-click them."

I have a prison with several doors I want to copy to the same Key. I Ctrl + Right-click and the door turns into an unlocked, normal door. Nothing else happens. I then go to the Key Item > Lock & Key tab > ID Keys and try to paste with Ctrl + Left-click and nothing is pasted. 
![2024-04-29 10_50_15-Foundry Virtual Tabletop](https://github.com/Saibot393/LocknKey/assets/88123390/e1b6ef3c-ed67-48f4-a85d-2955292e9079)

I also tried to use the included Macros and that does not seem to copy/paste either. I'm not sure if I'm misunderstanding how this should work, or this is an issue ?

Foundry v11 Build 315
D&D 5E v3.1.2
Lock & Key v2.7.7
Windows 11

**Comment by Saibot393** [comment]
This might be a misunderstanding, to paste an ID into a key you can right-click the item in the side bar and choose the option "paste IDs into key" from the context menu
![image](https://github.com/Saibot393/LocknKey/assets/137942782/b18d1d7d-f167-4c72-b7c5-2e828c095302)

**Comment by hmbaxharm** [comment]
Thank you - so the locked door has to be an item ? When I create a Key for a locked door, is the "ID key" the key's ID or the door's ID ?

Is there any way I can get the door IDs without having to make a new key for each one ?

**Comment by Saibot393** [comment]
So how the system works is a follows: Every key (item) and every lockable object (Doors, Token, Tiles) has a set of IDs. You can access these directly, for the items via the Lock & Key tab in the item settings ("ID keys"), for objects via the respective object settings (e.g. the wall settings for the door, see attached screenshot) under the L&K tab ("ID keys").
![image](https://github.com/Saibot393/LocknKey/assets/137942782/b3215b1e-4368-4f76-bd76-a3f933c52ecd)

Both keys and doors can have an arbitrary amount of these IDs, with these IDs being seperated by a ";" (btw. these IDs are not connected to any other default Foundry IDs like e.g. the walls id or the item ID).  If a key and a lock object have at least one matching ID, the key can open the door.

You can copy and paste key IDs between already existing objects/items. To copy you can use ctrl+right click on object, or use the copy option from the items context menu and to paste you can use ctrl+left click or use the paste option in the items context menu.

You can also directly create a new key for an object by shift+right clicking it, in this case this menu will open:
![image](https://github.com/Saibot393/LocknKey/assets/137942782/5ff757ba-736b-4e12-b861-94111926a421)

**Comment by hmbaxharm** [comment]
Thanks very much ! I didn't realize how I could access the door settings in the Wall configurations. I appreciate your help !
