### ISSUE TITLE
Use with MATT

### ISSUE THREAD

**Issue by Centor1982** [Saibot393/LocknKey#92]
It looks like there is an issue with the integration on Monk's Active Tile Triggers. Its giving an error when trying to inspect a tile with the filter by lock state. When chosing an entity (which is a tile) it gives an error of "Invalid Entity Type". While I suspect it may be written this way and can only inspect locked Tokens it seems like that is a limitation that doesnt make sence because the tiles can also be locked and are gennerally the focus of MATT's. Am I doing something wrong or is this a bug? If so is there a way to see if a tile is locked via attribute? Thanks!

**Comment by Saibot393** [comment]
Yes, i just saw your (?) questions on the foundry discord and decided to look into it and also noticed that i forgot to add tiles as a valid object type for the action, i am currently working on correcting that.

**Comment by Saibot393** [comment]
The MATT actions should now all work with tiles with the new v2.7.8
