### ISSUE TITLE
Correction of errors in localization into Russian.

### ISSUE THREAD

**Issue by maragondi** [Saibot393/LocknKey#93]
Correction of errors in localization into Russian.
I inspected the module today and noticed several errors. I couldn't understand the context. I'm sorry. Here is the corrected version. If an update suddenly comes out or I suddenly find an error again (I hope not ahaha) what can I just suggest a new version of the code in the lang section?
[rus.json](https://github.com/Saibot393/LocknKey/files/15287453/rus.json)

**Comment by Saibot393** [comment]
Thank you, the updated translation is included in v2.7.10.
If you have any other updates to the translation, feel free to open a nother issue here.
