### ISSUE TITLE
Request: Dialog on door interation

### ISSUE THREAD

**Issue by Durango807** [Saibot393/LocknKey#96]
My players can barely remember the keys for advantage and disadvantage - could there be an option for a dialog pop up when interacting with a door? 

Just show options to Open, Peek, Pick, or Break?

Bonus points to have the option to display DC for each choice.

**Comment by Saibot393** [comment]
There actually is already. Each player can choose a "Control sceme" in the settings, they can set it to "right-click popup-menu" to get a dialog with all available options.
An option to display the DC in said dialog is interesting, i will look into it.

**Comment by Saibot393** [comment]
I have added an option to show more details in the interaction menu with v3.1.0 ("Show DCs in interaction menu")
