### ISSUE TITLE
Door don't place as being configured default to "none"

### ISSUE THREAD

**Issue by gogrady4117** [Saibot393/LocknKey#98]
Doors do no default to a configured door instead they default to "none" and this is unable to be configured under module settings. This results in doors not having any sound when opened and closed.

**Comment by Saibot393** [comment]
is this under foundry v12?

**Comment by Saibot393** [comment]
I was able to replicat the behaviour, i will fix it as soon as possible

**Comment by Saibot393** [comment]
The bug should now be fixed wieth v3.0.2
