### ISSUE TITLE
Help resource or lockpick formula incompatibility

### ISSUE THREAD

**Issue by Hurtequin** [Saibot393/LocknKey#99]
I am using the Sandbox System Builder and I really like the idea of this module. However I am having some issues with the lockpick formula. How exactly should I go about determining the correct property path for a token. I have identified the property path for use in a roll dialog and it returns a correct value. However whenever I input the roll formula into the lockpick formula slot in settings it always returns a 0.

Some additional info:

in the chat messages and in a macro the formula "/r 1d12 + @attributes.num_opportunity.value" executes fine rolling 1d12 and adding the value of the selected tokens property.

When I copy and paste that formula into the lockpick formula in settings it always returns 1d12 + 0.

Any help in solving this would be appreciated.

**Comment by Saibot393** [comment]
To ensure system compatibility, lock & key formulas always start with @actor. Based on your formula, i think this should work: `@actor.attributes.num_opportunity.value`, if thats not the case, could you select one of your player tokens, enter this into the console (F12) and send me the output: `canvas.tokens.controlled[0].actor`, the output should look something like this:
![image](https://github.com/Saibot393/LocknKey/assets/137942782/9574567b-dd6b-4cf2-bf6e-a6f6a5b74b3b)

**Comment by Hurtequin** [comment]
adding "actor" did not solve the issue, it just fails to roll at all. Here is the actor data.
![image](https://github.com/Saibot393/LocknKey/assets/112917139/51c11450-5078-4a3b-aad7-b722f442ebae)

**Comment by Saibot393** [comment]
Then it might be `@actor.system.attributes.num_opportunity.value`, if thats not the case, could you send me the .json export of the actor?

**Comment by Saibot393** [comment]
Glad to hear that
